### ISSUE TITLE
[Research] React Native compatibility Android

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#1003]
## Context / issue

During our research [on React Native compatibility](https://github.com/safe-global/safe-core-sdk/issues/991) it was found that the SDK is compatible almost out of the box. The main challenge would be adding compatibility with passkeys. This was effectively tested for iOS, but we weren't able to validate this on Android.

## Proposed solution

For this ticket, the goal is to test that the SDK is equally compatible when using React Native with Android.
Passkeys + Android is out of the scope of this step

**Comment by yagopv** [comment]
[Research doc](https://www.notion.so/safe-global/Research-React-Native-compatibility-11c8180fe5738029902bf00a788b340b)
