### ISSUE TITLE
[Research] Passkeys and React Native in Android

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#1005]
## Context / issue

During our previous investigation we found the main pain point of the SDK with React Native is passkey management. For Android testing we will split Passkey management research from the main research as will be the most complex part.

## Proposed solution

Research how to use Passkeys with Android emulator and React Native.
From this research it should get some code snippets that show how to use passkeys with React Native ready to be used in the SDK

**Comment by yagopv** [comment]
[Research doc](https://www.notion.so/safe-global/Research-React-Native-compatibility-11c8180fe5738029902bf00a788b340b)
