### ISSUE TITLE
How do i transfer a token like usdc or usdt using safe sdk protocolkit ?

### ISSUE THREAD

**Issue by francelwebdev** [safe-global/safe-core-sdk#1045]
How do i transfer a token like usdc or usdt using safe sdk protocolkit ?

**Comment by dasanra** [comment]
You have an example in the 4337 playground. For protocol-kit Is exactly the same but calling the protocol-kit functions.

https://github.com/safe-global/safe-core-sdk/blob/014f365e46cf278897c5ece45c1490c7c749f2d7/playground/relay-kit/usdc-transfer-4337.ts#L46

There is also this answer [in Stack Exchange](https://ethereum.stackexchange.com/questions/116761/how-to-send-erc20-erc721-tokens-using-safe-core-sdk) that is the place to ask this kind of questions, as suggested by [our support guidelines.](https://github.com/safe-global/safe-core-sdk/blob/main/SUPPORT.md)

**Comment by dasanra** [comment]
But `Safe.createTransaction()` accepts the same transaction object than `Safe4337Pack.createTransaction()`. So the process to get the `transaction` object is the same.
