### ISSUE TITLE
Support EIP-712 signatures

### ISSUE THREAD

**Issue by rmeissner** [safe-global/safe-core-sdk#108]
## Context / issue

User should understand what they sign therefore we should support typed data signing

**Comment by lbhsot** [comment]
Any update on this? Or is there any workaround now?

**Comment by mehranhydary** [comment]
Hi there! Working on a multisig wallet for NFTs... would be awesome if this issue was prioritized so that our users know what messages they are signing through our dapp :)

Thanks!

**Comment by mehranhydary** [comment]
How would one go about fixing this? Let me know if it's something I can help out with!

**Comment by mehranhydary** [comment]
Hi there! Is this being tracked somewhere else?

**Comment by germartinez** [comment]
@mehranhydary I'm currently working on it

**Comment by mehranhydary** [comment]
@germartinez Awesome!! Thanks for the udpate

**Comment by lbhsot** [comment]
@germartinez Thanks for your work! Is there any plan to publish this feature?

**Comment by 0x7An** [comment]
🥇
