### ISSUE TITLE
createTransaction throws an error if the actual transaction fails

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-core-sdk#110]
## Description

safeSdk.createTransaction(contractInteractionTransaction) will fail if the actual transaction will revert

## Environment

- Safe Core SDK version: 1.0.0

## Steps to reproduce

Create a failing transaction

## Expected result

1. This is documented
2. Should there be a flag that allows skipping the check?

**Comment by dasanra** [comment]
After testing this issue, with Safes 1.3.0 onwards is possible to create transactions that wouldn't be successful at that exact moment.
