### ISSUE TITLE
More details on the purpose of each package/SDK and its intended use

### ISSUE THREAD

**Issue by marcin-trust** [safe-global/safe-core-sdk#114]
Hey, thanks for these great SDK libs! 
I've been wondering what the specific purpose of each of the packages is as listed in https://github.com/gnosis/safe-core-sdk#packages

Especially I had hard time figuring out how to add delegates using gnosis-core-sdk. It occurred that use case is supported in service client package.

So, could you
1) improve the details about purpose of each of the packages
2) provide an example use cases and limitations
3) maybe a rough sketch of the roadmap of what you plan for each of the SDKs.

That would help consume the libs with less confusion.

**Comment by germartinez** [comment]
Hello @marcin-trust,

Thank you very much for your feedback, it makes sense and adds value to the repo!

For `1)` I added this last week: https://github.com/gnosis/safe-core-sdk/tree/main/packages/guides (I'm referring to the README, not the guide). There you have an explanation of each package. Let me know if you find it useful or if you miss some information there. I will also try to make it easier to find and link to it from the README file in the root folder.

I'll try to improve `2)` by adding examples with real values for each method. I guess the [API Reference of the Safe Core SDK](https://github.com/gnosis/safe-core-sdk/tree/main/packages/safe-core-sdk) is a bit better documented than the [API Reference of the Safe Service Client](https://github.com/gnosis/safe-core-sdk/tree/main/packages/safe-service-client), but both are missing examples with values.

Regarding `3)`, for now you can check the open issues on this repo and follow the progress on these boards (filtered by safe-core-sdk repo):
- backlog: https://github.com/orgs/gnosis/projects/8?card_filter_query=repo%3Agnosis%2Fsafe-core-sdk
- sprints: https://github.com/orgs/gnosis/projects/17/views/11?filterQuery=repo%3Agnosis%2Fsafe-core-sdk

In the following weeks there will be a planning session and we will be able to provide a better roadmap overview.

Thank you!

**Comment by marcin-trust** [comment]
That's great answer, thx for detailed info @germartinez !
