### ISSUE TITLE
Follow EIP 1271 for contract signatures

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#14]
Follow EIP 1271 for contract signatures.
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1271.md

**Comment by mikheevm** [comment]
sandbox for signature validation: https://codesandbox.io/s/blissful-dewdney-sc25n?file=/src/is-valid-signature.ts

signature validation logic is taken from https://github.com/authereum/is-valid-signature

**Comment by yagopv** [comment]
As far as I understand we need to implement `isValidSignature` in some place in the repo

I implemented this in the [Monerium pack](https://github.com/safe-global/safe-core-sdk/blob/fc07ad724920b2a93602f86d61a994cc2e8d56b2/packages/onramp-kit/src/packs/monerium/SafeMoneriumClient.ts#L219-L262) indeed

**Comment by yagopv** [comment]
We created new tickets to handle the support of the EIP-1271 so going to close this one
