### ISSUE TITLE
For Safe Version 1.1.1, safeTxGas is always zero for multisend transactions

### ISSUE THREAD

**Issue by ryan-eiv** [safe-global/safe-core-sdk#168]
## Description

If you're using Safe Version 1.1.1, `safeTxGas` from  is always zero from `createTransaction`

## Environment

- Safe Core SDK version: 2.0.0
- Safe contract version: 1.1.1
- Environment:
  - browser: chrome

## Steps to reproduce

1. use a safe with version 1.1.1
2. create a multisend transaction with `createTransaction`
3. the transaction will have zero `safeTxGas` (this causes some transactions to fail with 1.1.1)

## Expected result

the transaction should have non-zero `safeTxGas`

## Additional context

It's probably because [`ethAdapter.estimateGas`](https://github.com/gnosis/safe-core-sdk/blob/db232e010611f98b1d5372168d7983b3284bb579/packages/safe-core-sdk/src/utils/transactions/gas.ts#L36) will error out from metamask with this message:
```
MetaMask - RPC Error: execution reverted: MultiSend should only be called via delegatecall 
```

**Comment by schmanu** [comment]
@germartinez I think I found the cause for this issue:
https://github.com/safe-global/safe-core-sdk/blob/399dbfca774cdc83b571b56583059e2fe5d18845/packages/safe-core-sdk/src/utils/transactions/gas.ts#L39
I think we need to pass the operation to this call.

I have the same issue when creating my updateSafe transactions using `createTransaction(tx[])`

**Comment by germartinez** [comment]
This has been fixed
