### ISSUE TITLE
Add comments to methods in the new packages 

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#171]
A couple of new packages were created in the monorepo and are missing comments that will be handled by TypeDoc to build the docs (like the `safe-core-sdk` package: https://gnosis.github.io/safe-core-sdk/).

Namely:
- `safe-web3-lib`
- `safe-ethers-lib`
- `safe-core-sdk-utils`

**Comment by yagopv** [comment]
Hey @germartinez. Is this still necessary after we revamp the repo and merge all these packages? Are we producing any automated docs?
