### ISSUE TITLE
Add a default fallback handler

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#183]
## Context / issue
Safes deployed by the Safe Core SDK can't receive NFT's automatically because the default falback handler is set to the zero address.

- Add a default fallback handler (https://github.com/gnosis/safe-core-sdk/blob/main/packages/safe-core-sdk/src/safeFactory/index.ts#L125)
- Add a method to replace the fallback handler (https://github.com/gnosis/safe-contracts/blob/main/contracts/base/FallbackManager.sol#L26)

**Comment by c-jain** [comment]
Hi @germartinez , I think you have opened this issue after looking at my [StackExchange](https://ethereum.stackexchange.com/questions/124516/safetransferfrom-of-erc721-not-working-when-transfering-nft-to-a-safe-address) post, right? 

Few more things to draw into your attention:

- Safes deployed by Safe Core SDK also can't receive ERC1155 NFTs automatically. Pls also consider this.
- There are so many Safes on Ethereum Mainnet deployed via our platform using Safe Core SDK. Can you pls share an easy to understanding steps to enable this default fallback handler things for already deployed Safes on Mainnet.
- Kindly consider resolving this issue asap.
