### ISSUE TITLE
Error when trying to load a Gnosis Safe v1.1.1

### ISSUE THREAD

**Issue by santteegt** [safe-global/safe-core-sdk#185]
## Description

I'm using `safe-core-sdk@2.0.0` to interact with a user Gnosis Safe. Those usually have been deployed using different versions of the Gnosis smart contracts (not all have been upgraded through the Gnosis App). Everything works fine however, I just realized that an error is always raised when calling the `Safe.create({.ethAdapter, safeAddress })` method with a safe address from a Gnosis contract wallet with version `1.1.1`. The stacktrace is the following: 

```
ERROR getSafe Error: You must provide the json interface of the contract when instantiating a contract object.
    at Object.ContractMissingABIError (errors.js:110:1)
    at Contract (index.js:76:1)
    at new Contract (index.js:309:1)
    at Web3Adapter.getContract (Web3Adapter.js:113:1)
    at Web3Adapter.getSafeContract (Web3Adapter.js:72:1)
    at ContractManager.getSafeContract (contractManager.js:121:1)
    at ContractManager.init (contractManager.js:78:1)
    at async Function.create (contractManager.js:45:1)
    at async Safe.init (Safe.js:100:1)
    at async Function.create (Safe.js:73:1)
```

## Environment

- Safe Core SDK version: 2.0.0
- Safe contract version: 1.1.1
- Environment:
  - browser (Google Chrome v99.0.4844.51)

## Steps to reproduce

- Example code for loading a Safe on Gnosis Chain

```
import Web3 from 'web3';
import Safe from '@gnosis.pm/safe-core-sdk';
import Web3Adapter from '@gnosis.pm/safe-web3-lib';

const rpcUrl = 'https://rpc.gnosischain.com/';
const web3 = new Web3(new Web3.providers.HttpProvider(rpcUrl));
const ethAdapter = new Web3Adapter({ web3 });
const safeAddress = '0xe8169d5b5287aa05082a9aa45f222075efeb68e1';
const safeSdk = await Safe.create({
      ethAdapter,
      safeAddress,
});
```

## Expected result

Should work with any version of the Safe smart contracts

**Comment by germartinez** [comment]
Added support to Safes with version `1.0.0` and `1.1.1` here: https://github.com/safe-global/safe-core-sdk/pull/285
