### ISSUE TITLE
web3 1.7.1 broken which breaks safe-ethers-lib

### ISSUE THREAD

**Issue by de33** [safe-global/safe-core-sdk#191]
## Description

The current safe-core-sdk uses web3 1.7.1, which breaks safe-ethers-lib due to a misconfiguration found and solved here:
https://github.com/ChainSafe/web3.js/issues/4926

## Environment

- Safe Core SDK version: 2.1.0
- Safe contract version: 1.3
- Environment:
  - browser

## Steps to reproduce

Importing and using EthersAdapter in any capacity will trigger a "module not found" error.

## Expected result

EthersAdapter should function as normal to allow interaction with safeSdk.

**Comment by germartinez** [comment]
Fixed here: https://github.com/safe-global/safe-core-sdk/pull/205
