### ISSUE TITLE
npm install / yarn failed on Apple M1 macOS device

### ISSUE THREAD

**Issue by chicunic** [safe-global/safe-core-sdk#192]
## Prerequisites

- First, many thanks for taking part in the community and helping us improve. We appreciate that a lot.
- Support questions are better asked in our Discord chat: https://discord.com/channels/477106835862716416/477391201708802058
- Please ensure the issue isn't already reported.

*Please delete the above section and the instructions in the sections below before submitting*

## Description

```
make: *** [Release/leveldb.a] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxx/safe-core-sdk/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command \"/Users/xxx/.nvm/versions/node/v16.14.2/bin/node\" \"/Users/xxx/safe-core-sdk/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/xxx/safe-core-sdk/node_modules/leveldown
```

## Environment

- Safe Core SDK version: 2.1.0
- Safe contract version: 
- Environment:
  - non-browser

## Steps to reproduce

If applicable, please provide a screenshot or small video reproducing the bug.
Provide as much information as necessary to reproduce the bug.

## Expected result

Please describe concisely what you expect instead.

**Comment by germartinez** [comment]
This should solve your issue: https://codeforgeek.com/make-failed-with-exit-code-2/
