### ISSUE TITLE
Property 'getAllTransactions' does not exist on type 'SafeServiceClient'

### ISSUE THREAD

**Issue by northloopfin** [safe-global/safe-core-sdk#195]
## Description

`const allTxs: SafeMultisigTransactionListResponse = await safeService.getAllTransactions(safeAddress)` does not work, I get a typescript error as per below:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/45414210/163876403-aac451c8-7d55-457c-94f2-3d15e89bb87c.png">

## Environment

- Safe Core SDK version: 1.0.1
- Safe contract version: 
- Environment: node 16 / yarn
  - browser
  - non-browser This

**Comment by germartinez** [comment]
Hi, `getAllTransactions` method was added in version `v1.1.0`. Please make sure you are using that version number or higher.
