### ISSUE TITLE
add options of prefix in  'getTxServiceBaseUrl' in safe-service-client

### ISSUE THREAD

**Issue by haike0513** [safe-global/safe-core-sdk#200]
## Context / issue

Why is this feature needed?

the tsServiceUrl on moonbase multisign is start with `https://gateway.multisig.moonbeam.network/v1/chains/1287`, so the safe-service-client can not use in moonbase.

## Proposed solution

add alternative options prefix in `getTxServiceBaseUrl`

```javascript
export function getTxServiceBaseUrl(txServiceUrl: string, prefix?: string): string {
  return `${txServiceUrl}/${prefix ?? 'api/v1'}`
}
```

**Comment by sirpy** [comment]
this seems to be relevant to all or many other chains safe UI deployments
