### ISSUE TITLE
Allow owner delegates to create transactions

### ISSUE THREAD

**Issue by microbecode** [safe-global/safe-core-sdk#211]
## Prerequisites

Allow submitting transactions as a Gnosis Safe multisig delegate owner.

## Context / issue

Multisig only allows owners to submit transaction (https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-core-sdk/src/Safe.ts#L341). Allow this also for delegated owners, since they are supposed to be able to submit transactions.

## Proposed solution

Extend the code to check for delegate permissions.

**Comment by germartinez** [comment]
Closing this issue because this was implemented here: https://github.com/safe-global/safe-core-sdk/pull/209
