### ISSUE TITLE
Wrong V value set for a signature

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-core-sdk#214]
## Description

Someone in discord reported the `proposeTransaction`errors for them with 422 returned by the backend when using Core SDK . This was the transaction:
```
baseGas: 0
contractTransactionHash: "0x4f075dca99ce1c0876c94336c4f5633490487cb6e1d29d3a7ee28a6844a767f9"
data: "0x"
gasPrice: 0
gasToken: "0x0000000000000000000000000000000000000000"
nonce: 4
operation: 0
refundReceiver: "0x0000000000000000000000000000000000000000"
safeTxGas: 0
sender: "0xBd0ac991250A827dE2014c06330fe50B4824E668"
signature: "0x70322a7d0e141ed86e7efc969ea569abbd11ebe3205536e8ea627df21d3df82c4c8881ed3bc305a179e376d719d0adabf4b29701c8ae8589f87719bb59b49ef520"
to: "0xf40D210e893A38a6c82Cd4F4074e67a081d1394b"
value: "100000000000000"
```

After checking the signature, it seems that the V value is incorrect. So, I used https://github.com/mikhailxyz/safe-signature-recovery to check the recovered address and the address was correct for the signature:
```
0x70322a7d0e141ed86e7efc969ea569abbd11ebe3205536e8ea627df21d3df82c4c8881ed3bc305a179e376d719d0adabf4b29701c8ae8589f87719bb59b49ef51c
```

V value is `0x1c` instead of `0x20`

## Environment
- Safe Core SDK version: 2.1.0 with web3.js

## Expected result

The backend accepts the signature

## Additional context
![image](https://user-images.githubusercontent.com/16622558/177808243-dad960ba-8330-4951-9ca2-d223591a5be0.png)
[Discord link](https://discord.com/channels/907968493134155807/960898410037272616/994609450994376736)

**Comment by willm30** [comment]
@mikhailxyz I ran into something similar. I changed the value from a string to a number (which conflicts with the `SafeTransactionDataPartial` type) and I received a 201 from the server instead.

**Comment by AlissonRS** [comment]
@mikhailxyz I'm facing an issue with `proposeTransaction`. Below is the exact object I'm passing as argument to it:

```
{
  safeAddress: '0x9CdaC53df578D3BDA98fe41Fc2CD6CEEB28DA644',
  safeTxHash: '0x9f438902e0769d019f86bd33c763de179bc8f82879a0d4c313fd48c95f7fb4e8',
  safeTransactionData: {
    to: '0x75542FbDC40BdAC7B16663a95Df8BF9C4C967143',
    value: '0x00',
    data: '0x00bbc2dc0000000000000000000000006ef251ec0b52f8f9c54905d8900de3e3522d7f37',
    operation: 0,
    baseGas: 0,
    gasPrice: 0,
    gasToken: '0x0000000000000000000000000000000000000000',
    refundReceiver: '0x0000000000000000000000000000000000000000',
    nonce: 11,
    safeTxGas: 0
  },
  senderAddress: '0xdeb9E55E0F20bC59029271372ECea50E67182A3A',
  senderSignature: '0xfd551d30943b136d435c1fba3300a5a1c767be7621f29402c9864b23d2cd3a6811e6eb78dd9711254636073178221de8fb6671e44911aafdbefd25c363426d0e1f'
}
```

I tried to execute it from the UI (which succeeds) and checked the POST call to the backend. Then I tried to replicate the request with a different contract address (but same ABI and argument), and my resulting query is as below:

```
POST https://safe-client.gnosis.io/v1/chains/43114/transactions/0x9CdaC53df578D3BDA98fe41Fc2CD6CEEB28DA644/propose

{
    "to": "0x75542FbDC40BdAC7B16663a95Df8BF9C4C967143",
    "value": "0",
    "data": "0x00bbc2dc0000000000000000000000006ef251ec0b52f8f9c54905d8900de3e3522d7f37",
    "operation": 0,
    "nonce": "11",
    "safeTxGas": "0",
    "baseGas": "0",
    "gasPrice": "0",
    "gasToken": "0x0000000000000000000000000000000000000000",
    "refundReceiver": "0x0000000000000000000000000000000000000000",
    "safeTxHash": "0xc1d1d29167a782fd3bcd074f70e7e8a293109092d87f1a53bc11c6588e0649ae",
    "sender": "0xdeb9E55E0F20bC59029271372ECea50E67182A3A",
    "origin": null,
    "signature": "0xfd551d30943b136d435c1fba3300a5a1c767be7621f29402c9864b23d2cd3a6811e6eb78dd9711254636073178221de8fb6671e44911aafdbefd25c363426d0e1f"
}
```

From what I can see, the only difference compared to the original request from UI which works is the `to` (which is a different contract address so that's expected) and the `signature`. So my understanding is that the signature here is invalid, this is the response I get from backend:

> 422 Unprocessable Entity
> {
    "code": 1337,
    "message": "{\"nonFieldErrors\":[\"Contract-transaction-hash=0x9f438902e0769d019f86bd33c763de179bc8f82879a0d4c313fd48c95f7fb4e8 does not match provided contract-tx-hash=0xc1d1d29167a782fd3bcd074f70e7e8a293109092d87f1a53bc11c6588e0649ae\"]}"
}

And this is how I create the signature:

```
 let safeTransactionData = {
    to: ethers.utils.getAddress(contractAddress),
    data,
    value: "0x00",
  };

  let safeTransaction = await safeSdk.createTransaction({ safeTransactionData });
  let safeTxHash = await safeSdk.getTransactionHash(safeTransaction);
  let senderSignature = await safeSdk.signTransactionHash(safeTxHash);
```

I'm following the guide on proposing txs, so I can only guess there is an issue with the library itself.

My gnosis packages:

>     "@gnosis.pm/safe-core-sdk": "3.1.1",
>     "@gnosis.pm/safe-core-sdk-types": "1.6.1",
>     "@gnosis.pm/safe-ethers-lib": "1.6.1",
>     "@gnosis.pm/safe-service-client": "^1.3.1",

**Comment by mikhailxyz** [comment]
@AlissonRS This is not related to the V value of the signature. It's a different problem. Could you please create a new issue and include a reproduction example? I tried to reproduce it but couldn't

**Comment by msinghnanhre** [comment]
@AlissonRS were you able to figure this out?

**Comment by AlissonRS** [comment]
@msinghnanhre I actually got back here by accident because I was trying this again, had the exact same issue, and when googling around I found this old thread.

I found a fix for this issue here: https://stackoverflow.com/questions/57116698/why-i-receive-422-unprocessable-entity-error-when-trying-to-post-data-to-api-u
