### ISSUE TITLE
`safeAddress` is mandatory even for deploying a Safe

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-core-sdk#225]
## Description

The type signature for `sdk.create` requires a `safeAddress`  even for deploying a safe.

The docs suggest that you can omit the `safeAddress` parameter when creating the SDK:
https://github.com/safe-global/safe-core-sdk/tree/main/packages/safe-core-sdk#2-deploy-a-new-safe

But if we check the type, it is required:
https://github.com/safe-global/safe-core-sdk/blob/d038b4f4fec812afc6f70f71e8a761cba5ac2974/packages/safe-core-sdk/src/Safe.ts#L36

## Environment

- Safe Core SDK version: 2.2.1
- Safe contract version: 
- Environment:
  - browser
  - non-browser

## Steps to reproduce
Follow deploy steps from the docs

## Expected result
No typescript error

**Comment by germartinez** [comment]
@mikhailxyz I think you are using the `Safe` class to deploy a new Safe, but is the `SafeFactory` class the one that should be used.

**Comment by mikhailxyz** [comment]
oops, sorry ser

**Comment by capit0** [comment]
@germartinez 

It was actually me who asked Mikhail while following this guide:

https://github.com/safe-global/safe-core-sdk/blob/6bef2d6d3df4eb455e73392fa48a0d16bf36b0b2/packages/guides/integrating-the-safe-core-sdk.md

At a certain point it begins to initialize the SDK like so:

```
import Safe, { SafeFactory } from '@gnosis.pm/safe-core-sdk'

const safeFactory = await SafeFactory.create({ ethAdapter })

const safeSdk = await Safe.create({ ethAdapter, safeAddress })
```

Are you saying that only the Factory line should be used? And if the safe is created through another safe, then what should be the input parameter of the `safeAddress`? Just the safe itself?

**Comment by germartinez** [comment]
@capit0 
1.
```
const safeFactory = await SafeFactory.create({ ethAdapter })
```
The main purpose of `safeFactory` is to deploy new Safes by calling the method `deploySafe()`. This method deploys a Safe and returns a `safeSdk` instance initialized with the new Safe.


2.
```
const safeSdk = await Safe.create({ ethAdapter, safeAddress })
```
On the other hand, `safeSdk` is the result of initializing the SDK with an existing Safe.

In both you end up with a `safeSdk`, is just depends if you need to deploy a Safe before or already have one to use it.
