### ISSUE TITLE
Add estimateGas method

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#227]
## Context / issue

Users want to know if a transaction will fail before it is executed.
```
if (!safeSdk.estimateGas(transaction)) {
  showWarning()
}
```

## Proposed solution

Add a `estimateGas(transaction)` method to the `Safe` class that calls this [method](https://github.com/safe-global/safe-core-sdk/blob/6bef2d6d3df4eb455e73392fa48a0d16bf36b0b2/packages/safe-web3-lib/src/contracts/GnosisSafe/GnosisSafeContractWeb3.ts#L123).

**Comment by JacqueGM** [comment]
This one would be very useful for us too!

**Comment by germartinez** [comment]
This was replace with #279
