### ISSUE TITLE
Error when calling signTransaction with eth_signTypedData option

### ISSUE THREAD

**Issue by cnaut** [safe-global/safe-core-sdk#238]
## Description
I am trying to call the signTransaction method of the safe-core-sdk with the eth_signTypedData signingMethod but I am receiving an error when attempting to do so. The error is in the browser console: "MetaMask - RPC Error: "params.data" must be an array"

## Environment
Safe core
- Safe Core SDK version:  2.3.2
- Environment: 
  - browser

## Steps to reproduce
Call the signTransaction method with the eth_signTypedData to reproduce. The method works when setting no signingMethod or setting signingMethod as eth_sign. 

![image](https://user-images.githubusercontent.com/372902/182672719-d5ae42ea-061b-4ccd-b141-015d96d13e72.png)

## Expected result

I'd expect the transaction to be signed according to the EIP-712.

**Comment by germartinez** [comment]
Hello @cnaut,
I was trying to reproduce the issue and it happens when using `web3.js` but it works correctly when using `ethers.js`.
Thanks for reporting, I'll check it.

**Comment by cnaut** [comment]
Thank you @germartinez! Do you have an ETA for when a fix could be made so I can decide if it is worth finding a workaround or switching to ethers?

**Comment by germartinez** [comment]
Not directly related with this PR, but fixed there: https://github.com/safe-global/safe-core-sdk/pull/285
To be released very soon
