### ISSUE TITLE
TypeError when executing 'safeService.proposeTransaction()'

### ISSUE THREAD

**Issue by Meyanis95** [safe-global/safe-core-sdk#239]
## Description

I have the following TypeError when executing 'safeService.proposeTransaction()'
![image](https://user-images.githubusercontent.com/67648863/182683792-6cf9e8d6-dd80-4dd6-b07d-84ff48ea1c5f.png)

```
  const createTransaction = async () => {
    const transaction = {
      to: recipientAddress,
      value: "2000000000000000",
      data: "0x",
    };
    const safeTransaction = await safeSdk.createTransaction(transaction);
    console.log(safeTransaction);
    const safeTxHash = await safeSdk.getTransactionHash(safeTransaction);
    const senderSignature = await safeSdk.signTransactionHash(safeTxHash);
    console.log({
      safeWalletAddress,
      safeTransactionData: safeTransaction.data,
      safeTxHash,
      userAddress,
      senderSignature: senderSignature,
    });
    await safeService.proposeTransaction({
      safeWalletAddress,
      safeTransactionData: safeTransaction.data,
      safeTxHash,
      userAddress,
      senderSignature: senderSignature.data,
    });
  };
```

## Environment

- Safe Core SDK version: "2.3.2"
- Safe contract version: "1.3.0"
- Environment:
  - browser: Chrome

## Steps to reproduce

"react": "^18.2.0",
"ethers": "^5.6.9"

Safe deployed on Rinkeby, and try to send a transaction on the same network

## Expected result

I can sign the transaction but when the is executing `const senderSignature = await safeSdk.signTransactionHash(safeTxHash);` The error above thows.

**Comment by germartinez** [comment]
Hello @Meyanis95,
Notice that the right properties for the object that is passed to the `proposeTransaction()` method are the ones specified here: https://github.com/safe-global/safe-core-sdk/tree/main/packages/safe-service-client#proposetransaction
```
const transactionConfig: ProposeTransactionProps = {
  safeAddress,
  safeTxHash,
  safeTransactionData,
  senderAddress,
  senderSignature,
  origin
}
``` 
Some are optional, but some you are using are incorrect
