### ISSUE TITLE
`EthersAdapter, SafeServiceClient`: Allow read-only methods to use a provider that doesn't have a signer

### ISSUE THREAD

**Issue by Evalir** [safe-global/safe-core-sdk#258]
## Context / issue

Right now, it's necessary to create a provider that can _sign_ transactions before using the SDK. This then imposes the need to connect to a wallet before the `SafeServiceClient` is usable.

While this is understandable for methods that interact with transactions, some methods, like `getBalances` just read data and do not need to sign anything. However, they're still unusable if you're not connected to a wallet, as you can't initialize the `SafeServiceClient` without an adapter, which in turn needs a signer.

## Proposed solution

Be able to create an `EthersAdapter` that can take a provider without a signer to use read-only methods.

## Alternatives

Querying the tx-service myself. However, I'd love to use all the safe packages instead of handrolling my own 🙏.

## Additional context

See the current [`EthersAdapter` guide](https://github.com/safe-global/safe-core-sdk/tree/main/packages/safe-ethers-lib#initialization).

**Comment by germartinez** [comment]
Working on this.
I'm replacing the `EthAdapter` constructor to this:
```js
const ethAdapter = new EthersAdapter({
  ethers,
  signerOrProvider
})
```
where `signerOrProvider` has type `Signer | Provider`

**Comment by Evalir** [comment]
Amazing to hear! Thanks for the response 🙏

**Comment by germartinez** [comment]
WIP: https://github.com/safe-global/safe-core-sdk/pull/260
