### ISSUE TITLE
Ability to retrieve Allowance Module instance

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-core-sdk#263]
## Context / issue

We are manually retrieving the Allowance Module contract instance whereas other deployments are loaded via the SDK.

## Proposed solution

Implement the ability to load the Allowance Module contracts via the SDK.

**Comment by germartinez** [comment]
I would say this task should stay out of the Safe Core SDK and stick to the Safe core contracts included in [safe-deployments ](https://github.com/safe-global/safe-deployments) package.
Although the Core SDK is used by our web interface, its functionality should remain generic and not implement logic for custom modules, guards, tokens, etc.
If the allowance module is added to [safe-deployments ](https://github.com/safe-global/safe-deployments) package, with all the addresses for the different networks, etc. I'm okay with it, but in general I think it should work only with the Safe core contracts.
