### ISSUE TITLE
safe ethers lib throwing error with new version1.6.0

### ISSUE THREAD

**Issue by c-jain** [safe-global/safe-core-sdk#267]
## Description

I was using `@gnosis.pm/safe-ethers-lib` version `1.1.0`. I switched to the newer version `1.6.0`, which throws the below error.
```javascript
Error: Cannot find module '../../typechain/src/ethers-v5/v1.1.1/factories/Gnosis_safe__factory'
Require stack:
- /app/node_modules/@gnosis.pm/safe-ethers-lib/dist/src/contracts/contractInstancesEthers.js
- /app/node_modules/@gnosis.pm/safe-ethers-lib/dist/src/EthersAdapter.js
- /app/node_modules/@gnosis.pm/safe-ethers-lib/dist/src/index.js
- /app/server/helpers/safecore-sdk.ts
- /app/server/helpers/index.ts
- /app/server/middlewares/errorLogger.ts
- /app/server/index.ts
- /app/app.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (/app/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._resolveFilename (/app/node_modules/tsconfig-paths/src/register.ts:115:36)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/@gnosis.pm/safe-ethers-lib/src/contracts/contractInstancesEthers.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/app/node_modules/ts-node/src/index.ts:1587:43) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/node_modules/@gnosis.pm/safe-ethers-lib/dist/src/contracts/contractInstancesEthers.js',
    '/app/node_modules/@gnosis.pm/safe-ethers-lib/dist/src/EthersAdapter.js',
    '/app/node_modules/@gnosis.pm/safe-ethers-lib/dist/src/index.js',
    '/app/server/helpers/safecore-sdk.ts',
    '/app/server/helpers/index.ts',
    '/app/server/middlewares/errorLogger.ts',
    '/app/server/index.ts',
    '/app/app.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also, not in Windows but on Mac, somehow `1.1.0` is now throwing the below error:
```javascript
ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.8.3)
Compilation error in /Users/nakul/Documents/projects/mesha/mesha-be/server/helpers/safecore-sdk.ts
[ERROR] 23:09:03 ⨯ Unable to compile TypeScript:
server/helpers/safecore-sdk.ts(44,45): error TS2740: Type 'EthersAdapter' is missing the following properties from type 'EthAdapter': getNonce, getChecksummedAddress, getMultiSendCallOnlyContract, getStorageAt, and 3 more.
```
This error was not there before switching to `1.6.0` and is now blocking us as it is occurring on Mac system and on the server.

## Environment

- Safe Core SDK version: 2.1.0
- Safe service client version: 1.0.1
- Node version: 16.13.1
- ts-node version: 10.8.2
- Environment:
  - non-browser

## Expected result

No error.

**Comment by len-cl** [comment]
Stuck with this issue as well !

**Comment by germartinez** [comment]
@c-jain @len-cl
Thanks for reporting, I'm working on fixing this issue.
Meanwhile, these are the latest version numbers prior to this issue that can be used:

- **safe-core-sdk**: `v3.0.0`
- **safe-service-client**: `v1.2.0`
- **safe-ethers-lib**: `v1.5.0`
- **safe-web3-lib**: `v1.5.0`
- **safe-core-sdk-types**: `v1.5.0`
- **safe-core-sdk-utils**: `v1.3.0`

**Comment by nakulthebuilder** [comment]
Still getting the following error with safe-ethers-lib v1.5.0:

`server/helpers/safecore-sdk.ts(44,45): error TS2740: Type 'EthersAdapter' is missing the following properties from type 'EthAdapter': getNonce, getChecksummedAddress, getMultiSendCallOnlyContract, getStorageAt, and 3 more.`

Temporarily fixed by setting the output to `any`

```
 const ethAdapter: any = new EthersAdapter({
      ethers,
      signer,
    });
```

**Comment by germartinez** [comment]
> Still getting the following error with safe-ethers-lib v1.5.0:
> 
> `server/helpers/safecore-sdk.ts(44,45): error TS2740: Type 'EthersAdapter' is missing the following properties from type 'EthAdapter': getNonce, getChecksummedAddress, getMultiSendCallOnlyContract, getStorageAt, and 3 more.`

Make sure to use safe-ethers-lib v1.5.0 with safe-core-sdk-types v1.5.0. That should be not related with this issue

**Comment by germartinez** [comment]
@c-jain @len-cl @motonauta @nakulthebuilder

Fixed here in the next release: https://github.com/safe-global/safe-core-sdk/releases/tag/r19

These are the new version numbers:
- **safe-core-sdk**: `v3.1.1`
- **safe-service-client**: `v1.3.1`
- **safe-ethers-lib**: `v1.6.1`
- **safe-web3-lib**: `v1.6.1`
- **safe-core-sdk-types**: `v1.6.1`
- **safe-core-sdk-utils**: `v1.4.1`
