### ISSUE TITLE
Having react issues using this package. Is this sdk only meant to be used on server side?

### ISSUE THREAD

**Issue by rajat-sr** [safe-global/safe-core-sdk#270]
## Prerequisites
I started using this package (along with `@gnosis.pm/safe-ethers-lib` and `@gnosis.pm/safe-service-client`) to propose transactions on Gnosis Safe. I'm using this package purely on frontend (React + Vite) and I am directly initiating a transaction proposal to Gnosis Safe from frontend without involving backend. 

## Description
The issue is that to use this package I need to polyfill `buffer` and `stream` packages which are NodeJS packages. This makes me question is this sdk only made to be used in the backend?

## Environment

- Safe Core SDK version: 3.0.0
- Safe contract version: 
- Environment:
  - browser

## Steps to reproduce
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/13731210/191819297-df6c8b8b-60d3-4dd8-9f5d-54ebd95e419a.png">

## Expected result
I should be able to use this package on react without involving backend.

**Comment by germartinez** [comment]
Hello @rajat-sr,
The Core SDK is meant to be used in the front-end or back-end
Please make sure where that requirement is coming from, as our own web interface uses the SDK and does not have those added: https://github.com/safe-global/web-core

**Comment by rajat-sr** [comment]
Great to know this can be used on frontend as well. 

The requirement is coming from the SDK itself. I looked into your web interface repo. Looks like it's using NextJS which has both `buffer` and `stream` as its dependencies which is probably why you never faced this problem. Vite requires me to polyfill these packages. 

Anyway thanks for the response @germartinez! You've been a huge help.

**Comment by NicoHalpe** [comment]
Hi, I am having trouble when building my vite app to production. It crashes with this error: `TypeError: Cannot read properties of undefined (reading 'call')`. Have you faced this issue? And if not, can you post your vite config file?
