### ISSUE TITLE
Link to the guide in the README.md is no longer working.

### ISSUE THREAD

**Issue by adriandelgg** [safe-global/safe-core-sdk#280]
When you go to the README of this project and click on the "guide" which is on the first paragraph, the link gives a 404 error since it's no longer working.

https://github.com/safe-global/safe-core-sdk/tree/main/packages/safe-core-sdk#getting-started
It's the word guide in this paragraph.

What is the new link to the guide it talks about?

**Comment by germartinez** [comment]
Hello Adrian!

Thank you for reporting it. It is now fixed.

Happy hacking!
