### ISSUE TITLE
Support Safe v1.0.0 contracts

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#284]
## Context / issue

Currently the Core SDK only supports Safe v1.1.1, v1.2.0 and v1.3.0.
It makes sense to add v1.0.0 as well, as there are some Safe accounts with this version that are still in use.

## Proposed solution
- [x] [Add the ProxyFactory contract v1.0.0](https://github.com/safe-global/safe-deployments/pull/151) to `safe-deployments`
- [x] [~~Add the MultiSend contract v1.0.0~~](https://github.com/safe-global/safe-deployments/pull/152) ~~to `safe-deployments`~~ `MultiSend v1.0.0` should not be used due to an issue with `autodestruct`. Use a later version. Removed [here](https://github.com/safe-global/safe-deployments/pull/154)
- [x] [Support v1.0.0 in the Core SDK](https://github.com/safe-global/safe-core-sdk/pull/285)
- [x] [Support v1.1.1 in the Core SDK](https://github.com/safe-global/safe-core-sdk/pull/285)

**Comment by czepluch** [comment]
Would love to see this happen before the 27th (claim deadline).

**Comment by mikhailxyz** [comment]
@czepluch this is unlikely to happen. You can claim using the old app at https://gnosis-safe.io/app
