### ISSUE TITLE
Ethers Adapter assigning signer to #provider 

### ISSUE THREAD

**Issue by bill-ov** [safe-global/safe-core-sdk#303]
## Description

After instantiating EthersAdapter, the signer is undefined while provider gets the signer that I put in signerOrProvider 

## Environment

- Safe Core SDK version: 3.2.0
- Safe contract version: 1.7.0
- Environment: Node v16.17.1

## Steps to reproduce

```
import { ethers } from "ethers";
import EthersAdapter from "@gnosis.pm/safe-ethers-lib";

const provider = new ethers.providers.JsonRpcProvider("...");
const signer = provider.getSigner();
const ethAdapter = new EthersAdapter({ ethers, signer });

console.log('EtherAdapter signer: ', ethAdapter.getSigner())
    console.log('EtherAdapter provider: ', ethAdapter.getProvider())
```
The signer is undefined and the provider has the signer
## Expected result

The #signer should contain the signer instead of #provider

## Additional context

There might be a problem with your condition in EthersAdapter.ts on line 51. When I passed a JsonRpcSigner object to signerOrProvider, isSigner in line 51 turns to false since JsonRpcSigner is not an instanceof Signer despite being inherited by JsonRpcSigner. Instead of using the "instanceof Signer" to identify the value as a signer, I believe that you need to use the isSigner function to identify if it is a signer or not because I can't sign after creating transactions.

https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-ethers-lib/src/EthersAdapter.ts#L51

**Comment by bill-ov** [comment]
Feel free to comment if there's a reason why you used "signerOrProvider instanceof Signer" as a condition

**Comment by germartinez** [comment]
Hello @bill-ov,
I see the issue was close. Did you manage to  solve it or is it still happening in the SDK?

**Comment by germartinez** [comment]
After checking it I see that the documentation regarding `EthersAdatper` class was not updated after the changes in the constructor were pushed. I just fixed them [here](https://github.com/safe-global/safe-core-sdk/pull/304) and after replacing `signer` with `signerOrProvider` in your code the issue should be fixed. Let me know ;)
