### ISSUE TITLE
SafeProxy contract is not deployed on the current network - Polygon Mainnet

### ISSUE THREAD

**Issue by sourav-bz** [safe-global/safe-core-sdk#311]
## Description

This started occurring after the migration from gnosis SDK to the new SAFE npm module.
This is getting triggered on this line of code.
`safeSdk = await Safe.create({ ethAdapter, safeAddress: this.safeAddress! })`

The complete code looks something like this:

`const provider = new ethers.providers.Web3Provider(window.ethereum)`
`await provider.send('eth_requestAccounts', [])`

`const signer = provider.getSigner()`
`const ethAdapter = new EthersAdapter({`
	`ethers,`
	`signerOrProvider: signer,`
`})`

`let safeSdk = await Safe.create({ ethAdapter, safeAddress: this.safeAddress! })`

## Environment

- Safe Core SDK version: ^3.2.0
- Safe contract version: 
- Environment:
  - browser

## Steps to reproduce

![image](https://user-images.githubusercontent.com/22414946/207694428-1c927be7-05d9-4684-8654-d35c22ed0e0e.png)

## Expected result

I am initialising safeSdk to use .isOwner method. Which returns if the user address is the owner of the safe or not.
This started with Goerli network initially and now happening on polygon mainnet too.

**Comment by germartinez** [comment]
Hello @sourav-bz
I could not reproduce this issue.

Can you provide the RPC that you are using?
Does `this.safeAddress!` have a value and is it actually deployed on Polygon?

**Comment by sourav-bz** [comment]
Goerli RPC: `https://safe-transaction.goerli.gnosis.io/`
Goerli SAFE address: `0x3ECB8f4d6F8D2f41283f22F0ceaC0135d8dE6938`
This worked intermittently and started showing the above issue again. 
Not really sure where I am going wrong here, because it was working fine until the hard upgrade that happened.

**Comment by sourav-bz** [comment]
Hey, this was happening because the metamask was on different network. This is resolved. thanks 🙏
