### ISSUE TITLE
No exported member `SafeMultisigTransactionResponse` in `safe-core-sdk-types`

### ISSUE THREAD

**Issue by 0xnexusflip** [safe-global/safe-core-sdk#312]
## Description

When trying to import `Safe` from `@safe-global/safe-core-sdk` and compiling a resulting TypeScript file that uses it the following error shows up:

```
error TS2305: Module '"@safe-global/safe-core-sdk-types"' has no exported member 'SafeMultisigTransactionResponse'.

import { EthAdapter, MetaTransactionData, SafeMultisigTransactionResponse, SafeTransaction, SafeTransactionDataPartial, SafeVersion, TransactionOptions, TransactionResult } from '@safe-global/safe-core-sdk-types';

Found 1 error in node_modules/@safe-global/safe-core-sdk/dist/src/Safe.d.ts:2
```

## Environment

- Safe Core SDK version: 3.2.1
- Safe Core SDK Types version: 1.7.0
- Environment:
  - non-browser

## Steps to reproduce

- Import `Safe` from `@safe-global/safe-core-sdk` in a TypeScript file
- Attempt compiling the file using the `tsc` command in a terminal instance

Current result:
<img width="1391" alt="TS_compile_error_Safe_SDK" src="https://user-images.githubusercontent.com/112392940/207984750-8ddd0d5e-06de-4ac6-ab0f-e00b85316b43.png">

## Expected result

Expect `SafeMultisigTransactionResponse` to be imported when using `Safe` from `@safe-global/safe-core-sdk`

**Comment by sourav-bz** [comment]
facing the same issue.

**Comment by richikchanda1999** [comment]
Having the same issue, since yesterday.

**Comment by swetshaw** [comment]
Thanks @0xnexusflip for raising this issue, can any one from the safe team @germartinez @rmeissner please help 🙏. Our dApp is built on top of Safe and now it has stopped working because of this issue.

**Comment by germartinez** [comment]
Thanks for reporting it, I'll check it and fix it as soon as possible. Meanwhile please use the previous version.

**Comment by 0xnexusflip** [comment]
Using the '@gnosis.pm/safe-core-sdk' library seems to fix the issue but then when actually running the script I encounter issue #287

**Comment by germartinez** [comment]
@0xnexusflip @sourav-bz @richikchanda1999 @swetshaw 
New versions of all the Safe Core SDK packages have been published. Please check again

Specifically:
- safe-core-sdk `v3.2.2`
- safe-core-sdk-types `v1.6.0`
- safe-core-sdk-utils: `v1.8.0`
- safe-web3-lib: `v1.8.0`
- safe-ethers-lib: `v1.8.0`
- safe-service-client: `v1.5.0`
