### ISSUE TITLE
Can't Create Transaction when updated to @safe-global/safe-service-client

### ISSUE THREAD

**Issue by ArpitaGanatra** [safe-global/safe-core-sdk#313]
## Description

Once I fetch the transaction from safe-service-client library, I can't create a new transaction using `safeSdk.createTransaction({ safetx });`

My fetched transaction is as given below:
<img width="735" alt="Screenshot 2022-12-17 at 2 08 43 PM" src="https://user-images.githubusercontent.com/35517007/208233607-c8e7a08c-e224-4a93-9fb7-2eec9ea78f04.png">

and then I create a new transaction using ` const safetx2 = await safeSdk.createTransaction({ safetx });`
the error that I get:

<img width="735" alt="Screenshot 2022-12-17 at 2 10 06 PM" src="https://user-images.githubusercontent.com/35517007/208233655-4a65f978-6eb8-4181-93f2-91e1d9eff1db.png">

## Environment

I have recently updated the imports from `@gnosis.pm/safe-service-client` to `@safe-global/safe-service-client` and then this error started to appear.

**Comment by germartinez** [comment]
Hello @ArpitaGanatra,
It looks like you should update of your `safetx` variable to `safeTransactionData`

https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-core-sdk/src/Safe.ts#L320

Or call the method this way:

` ` `
.createTransaction({ safeTransactionData: safetx })
` ` `
