### ISSUE TITLE
Cannot propose transaction in browser environment

### ISSUE THREAD

**Issue by milli-xpn** [safe-global/safe-core-sdk#323]
## Description

I am running into an issue where I cannot propose a transaction through the safe-core-sdk and safe-service-client when running this code in our react application in the browser.

I am constructing a multisig transaction with the relevant libraries following [this guide](https://github.com/safe-global/safe-core-sdk/blob/main/guides/integrating-the-safe-core-sdk.md)

When it comes to calling `proposeTransaction` my application will throw with error `createKeccakHash is not a function`.

## Environment

- Safe Core SDK version: ^3.2.0
- Safe contract version: ?
- Environment:
  - browser

## Steps to reproduce
 
Following the stack trace, this comes from the following:
- `SafeServiceClient.proposeTransaction` calls a method [`getEip3770Address`](https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-service-client/src/SafeServiceClient.ts#L410) which calls `validateEip3770Address` from the safe-core-sdk-utils which then calls `validateEthereumAddress` which uses the package web3-utils `isAddress` method which has a dependency on node cryptography libraries which do not exist in the browser. 

To get around this problem temporarily, I have patched the library to bypass the validation [here](https://github.com/safe-global/safe-core-sdk/blob/main/packages/safe-core-sdk-utils/src/eip-3770/index.ts#L32) and the proposal is able to go through.

I have not found a way to polyfil this and get this to work in the browser without patching. I am using webpack as my bundler. 

## Expected result

To be able to propose and execute a transaction using safe-core-sdk libraries in react/browser code.

**Comment by NicoHalpe** [comment]
@germartinez any update on this? The `isAddress` function is not working on browser, which is throwing errors on my site when I run it on production (sice I can not patch it).

**Comment by dasanra** [comment]
The function was migrated to use `ethers` instead of `web3` in the latest `@safe-global/protocol-kit v4.0.0`.
