### ISSUE TITLE
Make safe class extendable

### ISSUE THREAD

**Issue by NicoHalpe** [safe-global/safe-core-sdk#326]
## Context / issue

I am working on a project so I am trying to extend the Safe class with my own functions, the problem is that I can not initialize the Safe with the `super()`, since the only way to initialize a safe is by using `Safe.create()`

## Proposed solution

Make the `init` method public.
The init method is what I need to instantiate the Safe from my extended class, but it is set private.

## Alternatives

Make another function to initialize a safe with an instance created using `Safe()`, not `Safe.create()`

## Additional comments

If there is a way to do this, I would appreciate some help :)

**Comment by yagopv** [comment]
Hey @NicoHalpe we don't have plans to open the `init` method 🙁. We want to force calling the `create`
