### ISSUE TITLE
Transaction fails when gasPrice is set via createTransaction and safe does not have enough MATIC

### ISSUE THREAD

**Issue by piyushhanchate** [safe-global/safe-core-sdk#333]
## Description

Used the safe-core-sdk to place a transaction (fetched as is from 1inch API) with gasPrice set. The transaction failed with `GS011` error. 

Sample: 0xa06cdd52f22d4cc99e0a764252a30cbb0ee432c8ff7e3f6cd7a193bb8eecec2d

## Environment

- Safe Core SDK version: Latest
- Safe contract version:  Latest
- Environment:
  - browser

## Steps to reproduce

Together with the transaction above. A separate transaction is created that sends MATIC tokens from safe to executing wallet
Sample: 0x4bb504beb328576ff9e86660c37763f9c5d8b21433e5a320f5f3d3f48e1033bd

Transactions:

https://polygonscan.com/tx/0x70e52a11717bb5cd303d4b8031e3f274ac4d9cc5918fa6faa8c232bd5d4827bd
https://polygonscan.com/tx/0xa06cdd52f22d4cc99e0a764252a30cbb0ee432c8ff7e3f6cd7a193bb8eecec2d
https://polygonscan.com/tx/0x35fb85a5c5e1ff29ce1e210a8febb86d70185e6b6081bda0a6c78961a4ff08a5

## Additional context
 
`function handlePayment( uint256 gasUsed, uint256 baseGas, uint256 gasPrice, address gasToken, address payable refundReceiver ) private returns (uint256 payment) {
 // solhint-disable-next-line avoid-tx-origin 
address payable receiver = refundReceiver == address(0) ? payable(tx.origin) : refundReceiver;
 if (gasToken == address(0)) {
 // For ETH we will only adjust the gas price to not be higher than the actual used gas price
 payment = gasUsed.add(baseGas).mul(gasPrice < tx.gasprice ? gasPrice : tx.gasprice); 
require(receiver.send(payment), "GS011"); } 
else { payment = gasUsed.add(baseGas).mul(gasPrice); 
require(transferToken(gasToken, receiver, payment), "GS012"); } }`

I think this is the relevant function being called here by:

 `if (gasPrice > 0) { payment = handlePayment(gasUsed, baseGas, gasPrice, gasToken, refundReceiver); }
in execTransaction()`

The transaction succeeds when I set the gasPrice to zero. But this isn't desirable behaviour, since we'd want to set gasPrice based on urgency.

**Comment by mikhailxyz** [comment]
The safe transaction `gasPrice` is intended to be used for the refund logic for meta transactions, and it seems like it is not what you're trying to achieve. You should use Ethereum's transaction gas price

**Comment by piyushhanchate** [comment]
I'm setting the gasPrice in ethers-js, like I usually do. Seems like createTransaction considers it to be the gasPrice you were referring to. Could you guide me towards how I could set Ethereum's transaction gas price, when using the safeCore SDK?

**Comment by mikhailxyz** [comment]
@piyushhanchate could you please provide an example of your code?
