### ISSUE TITLE
Non-editable options for proposals.

### ISSUE THREAD

**Issue by VKapicyn** [safe-global/safe-core-sdk#334]
Hi!
I need to create some proposals and so i need to specify options with the correct "nonce", but these options are skipped here.
[https://github.com/safe-global/safe-core-sdk/blob/53a21d693467a3c1e47fe30fa4db28b4374af1b5/packages/safe-core-sdk/src/Safe.ts#L345-L347](https://github.com/safe-global/safe-core-sdk/blob/53a21d693467a3c1e47fe30fa4db28b4374af1b5/packages/safe-core-sdk/src/Safe.ts#L345-L347)
My goal is to create proposals, which will be approved one by one. 
And one more important point, txs shouldn't be packaged in MultiTx, bcs each of them can exceed the gas limit.

Maybe this code is more correct?
`newTransaction = isMetaTransactionArray(safeTransactionData)`  
 `       ? { ...options, ...safeTransactionData[0] }`
`       : { ...options, ...safeTransactionData }`

**Comment by dasanra** [comment]
@VKapicyn thank you for your report. 

When using safeTransactionData can accept an array or an object. You had two options there to do what you were trying to do:
 - When used as an object could optionally get the same properties used in `options` so you could already set the nonce inside the object.
  - You could pass an array with only 1 transaction and use the `options` field as normal.
  
  As this "flexibility" is causing confusion we are going to change the function to accept an array only, that will be enough to cover all cases.
