### ISSUE TITLE
Export `EthSignSignature` from '@safe-global/safe-core-sdk'

### ISSUE THREAD

**Issue by fonstack** [safe-global/safe-core-sdk#394]
Now we have to import it from `@safe-global/safe-core-sdk/dist/src/utils/signatures/SafeSignature`

**Comment by germartinez** [comment]
Hi @fonstack,
Could you please elaborate a little bit why do you need and how are you using that class?

**Comment by fonstack** [comment]
Hey @germartinez,
I'm collecting the signatures by ourselves. We are storing the signatures on our database. Once all the signatures are collected we are creating the TX with:
`const safeTransaction = safeSdk.createTransaction`

After that I need to add all the signatures to the transaction, and in order to do that I'm using: 
`safeTransaction.addSignature(new EthSignSignature(signature.signerAddress, signature.signature))`

The `signature` object is the one saved in my database.

**Comment by germartinez** [comment]
Fair enough. I will implement this. Thanks for sharing your user-case.

**Comment by germartinez** [comment]
@fonstack check #405 to follow the progress on this ;)
