### ISSUE TITLE
.getUsdBalances() & .getCollectibles() were both removed...

### ISSUE THREAD

**Issue by codeonblocks** [safe-global/safe-core-sdk#396]
## Context / issue

Why is this feature needed?

It was very useful & our application was relying on it. If it won't come back, how can I get these same results elsewhere?

## Proposed solution

Add it back.

## Alternatives

Provide me with a guide to use it else where

**Comment by germartinez** [comment]
Those were not efficient endpoints in our service and were removed.
There are better services to retrieve this information like the APIs from Coingecko, Zerion, etc.

**Comment by codeonblocks** [comment]
Hey German, I took a look at those 2 options you shared, but they don't provide the same functionality that `.getUsdBalances()` & `.getCollectibles()` provided.

Do you know of any third-party APIs/libraries that allow you to get all ERC20 tokens & NFTs (ERC721/1155) from a given wallet address?

Or are you able to link me to where you previously provided that API so that I can fork it or study the code on how it was implemented?
