### ISSUE TITLE
Feature request: Python support for account abstraction using safe

### ISSUE THREAD

**Issue by 0x0elliot** [safe-global/safe-core-sdk#400]
I am not sure if this is better put in <a href="https://github.com/safe-global/safe-eth-py">here</a> but there is a heavy need for safe wallet SDK support for AA with python and clear documentation for it.

**Comment by germartinez** [comment]
Hello @0x0elliot,

Talking about Safe AA SDK, this is the place. The repo you linked it is implemented on Python, but not AA focused. However, as you see, this AA SDK is implemented in TypeScript.

There are solutions like [Polywrap](https://polywrap.io/) that allow to "wrap" an SDK, upload the code to IPFS and consume it from anywhere using a Polywrap client. We had some conversations with them and there is already some work done on that regard, but is does not cover AA featuers. Also their Python client is not available yet, maybe at some point.

Your request won't be available anytime soon, but if you have some data that shows that "heavy need", that would be great for us and maybe help us reprioritize some things.

I'm closing the issue as there is no action that can be taken at this moment.
