### ISSUE TITLE
Ethers v6 support for adapter

### ISSUE THREAD

**Issue by imaksp** [safe-global/safe-core-sdk#401]
## Context / issue

Why is this feature needed?

Ethers lib is now focusing on v6 (currently at 6.3), new v5 version has not been released from long time. so consider adding v6 support.

## Alternatives
Had to use ethers v5

**Comment by microHoffman** [comment]
It would be very useful to have Ethers v6 support as most of the projects will migrate to v6 anyway soon or later... is there any timeline on when it could be?

**Comment by aksdevac** [comment]
Adding for info:
[Web3 4.x](https://docs.web3js.org/docs/guides/web3_migration_guide/web3_eth_migration_guide) & [Ethers v6](https://docs.ethers.org/v6/single-page/#migrating__migrate-bigint) both supports JS BigInt type.
so it will also solve issue #413.

**Comment by DimaStebaev** [comment]
I really want this issue to be solved.
@DaniSomoza how can I help you with the implementation?

**Comment by DaniSomoza** [comment]
Hi @DimaStebaev

I'm currently working on it. 

Apologies for the late response.

**Comment by rmeissner** [comment]
This issue will be closed in favor of multiple smaller issues to handle this task:

- https://github.com/safe-global/safe-core-sdk/issues/544
- https://github.com/safe-global/safe-core-sdk/issues/545
- https://github.com/safe-global/safe-core-sdk/issues/546
- https://github.com/safe-global/safe-core-sdk/issues/547
- https://github.com/safe-global/safe-core-sdk/issues/548
