### ISSUE TITLE
Add support for smart contract signatures

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-core-sdk#407]
## Context / issue
Currently it is not possible to create dynamic EIP-1271 signatures through the safe-core-sdk.
These are important for smart contract signatures such as Safes or other smart contract wallets as Safe owners.

## Proposed solution
We should add a separate `SmartContractSignature` or `EIP1271Signature` implementation of `SafeSignature`.

Therefore we should add back the `offset` parameter to the `staticPart` function in order to easily provide the pointer to the start of the `dynamicPart`.

## Alternatives
Alternatively we could leave the parameters of the functions as they are and implement the EIP1271 Signature like this:
```ts
export class EIP1271Signature implements SafeSignature {
  constructor(public signer: string, public data: string, private offset: number) {}

  staticPart(): string {
    return hexZeroPad(this.signer, 32) + hexZeroPad(hexlify(this.offset), 32).slice(2) + '00'
  }
  dynamicPart(): string {
    const byteLength = hexZeroPad(hexlify(this.data.slice(2).length / 2), 32)
    return (byteLength + this.data.slice(2)).slice(2)
  }
}
```

Then the dapps would have to keep track of the current signature and pass in the offset in the constructor.

## Additional context
With this feature we could easily support all kinds of smart contract wallet in our Safe{Wallet}

**Comment by dasanra** [comment]
Implemented in https://github.com/safe-global/safe-core-sdk/pull/556
