### ISSUE TITLE
Add the possibility of showing `data` decoded on `signTypedData`

### ISSUE THREAD

**Issue by fonstack** [safe-global/safe-core-sdk#409]
Hey all <3 

I'm using `signTypedData` method, and I"m receiving this metamask prompt:
![CleanShot 2023-04-18 at 16 53 36](https://user-images.githubusercontent.com/35873992/232833953-32506d9e-36a8-4c4c-8164-3f20c12ec470.png)

That's ok and it's expected. But for the user singing the TX, it is not easy to know what they are signing (because the `data` property is encoded in bytes). Would be amazing if we can show that `data` property decoded. Something like:

```
{
   To: 0x00000000000
   Value: 0
   Data: encodedData
   DecodedData: ContractFunction(param1, param2, param3)
}
```

**Comment by mmv08** [comment]
This is a feature request for Metamask, not safe sdk
