### ISSUE TITLE
TypeError: Safe.create is not a function

### ISSUE THREAD

**Issue by ipatka** [safe-global/safe-core-sdk#419]
## Description

When importing the Safe class to connect with an existing Safe, it does not import the right module. Instead importing the rest of the module.

## Environment

- Safe Core SDK version: latest
- Safe contract version: 
- Environment:
  - non-browser

## Steps to reproduce

```
import 'dotenv/config'
import { Wallet, ethers } from 'ethers'

import Safe from '@safe-global/protocol-kit'
import { EthersAdapter } from '@safe-global/protocol-kit'
import { SafeTransactionDataPartial } from '@safe-global/safe-core-sdk-types'

const safeAddress = 'REDACTED'

const send = async () => {
    const pk = process.env.PRIVATE_KEY_1
    if (!pk) throw new Error('could not load key')

    const web3Provider = new ethers.providers.InfuraProvider('goerli', `REDACTED`)
    const signer = new Wallet(pk, web3Provider)

    const ethAdapter = new EthersAdapter({
        ethers,
        signerOrProvider: signer,
    })
    console.log({Safe})
    const safeSdk: Safe = await Safe.create({ ethAdapter, safeAddress})
    const safeTransactionData: SafeTransactionDataPartial = {
        to: '0x<address>',
        value: ethers.utils.formatUnits('0.2', 'ether'),
        data: '0x',
    }
    const safeTransaction = await safeSdk.createTransaction({ safeTransactionData })
    console.log({ safeTransaction })

}

send()
```

## Expected result

Safe connection works

## Additional context

Maybe there's a name collision in src/index.ts? export default Safe doesn't seem to work. The exports on lines 57-103 are getting imported.

Possibly related
https://github.com/safe-global/safe-core-sdk/issues/411

**Comment by ipatka** [comment]
Current workaround:

```
import SafeProtocol from '@safe-global/protocol-kit'

    const Safe = SafeProtocol.default
    const safeSdk: Safe = await Safe.create({ ethAdapter, safeAddress})
```

**Comment by royalaid** [comment]
Thanks for posting, no idea what is going on internally to require this hack but it worked for me

**Comment by dasanra** [comment]
Seems related to this
https://github.com/safe-global/safe-core-sdk/issues/243

**Comment by yagopv** [comment]
Hey @ipatka. I have some questions:

1) Are you running this in a node environment (no browser) ? 
2) Could you provide your typescript compilation settings and package.json ?
3) Are you compiling to esm instead cjs ?

Thanks!

**Comment by mmv08** [comment]
> Hey @ipatka. I have some questions:
> 
> 1. Are you running this in a node environment (no browser) ?
> 2. Could you provide your typescript compilation settings and package.json ?
> 3. Are you compiling to esm instead cjs ?
> 
> Thanks!

It can be reproduced in node when using ESM

**Comment by yagopv** [comment]
We are compiling to commonjs the `safe-core-sdk` project so guess the problem is here (node esm project outside the browser trying to import cjs). We probably need to do a dual compilation setup to cjs and esm detecting the usage of the type module. 

But when creating a simple node project to test i have an error even before (Safe is not a constructor). For this reason i want to know the exact configuration @ipatka is using with TS

**Comment by yagopv** [comment]
For now when using `safe-core-sdk` outside the browser (node) with ESM Modules the proposed hack works. We opened an [issue](https://github.com/safe-global/safe-core-sdk/issues/514) for changing the way we are building the `safe-core-sdk` and avoid this kind of hack

**Comment by yagopv** [comment]
Thanks!

**Comment by jmrossy** [comment]
Seeing the same problem when my TSConfig is using module and/or moduleResolution `node16` or `nodenext`
