### ISSUE TITLE
Unable to transfer ERC-20 & 721 token using safe core sdk.

### ISSUE THREAD

**Issue by Aayush3Intervision** [safe-global/safe-core-sdk#448]
## Token Transfer
I show ERC-20 & 721 tokens can be transfer using encode data into byte but unfortunately it is not working in mumbai (polygon) network.

**Comment by germartinez** [comment]
Hi @Aayush3Intervision,
Can you show how are you trying it and what is it failing?

**Comment by Aayush3Intervision** [comment]
Hi @germartinez,
I think it was network issue might be but right now it is working fine in sdk, and I am trying to do transaction using my custom smart contract with safe account so the transaction getting failed. 
Thank you for your support.
