### ISSUE TITLE
[Tooling] Coverage report

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#454]
## Context / issue

Currently we have plenty of tests and a coverage report generated after the tests. We can show the % of lines covered but there is no easy way to check if the tests are effectively covering the important paths.

## Proposed solution

Evaluate and configure a coverage report tool where we can upload the tests report after the Github action is executed. This tool should be able to separate branch runs or PRs showing the result of each of them.

There are two main options for coverage reports

- CodeCov
- Coveralls

**Comment by germartinez** [comment]
Implemented here: https://github.com/safe-global/safe-core-sdk/pull/470
`protocol-kit` is missing this. More info in the PR
