### ISSUE TITLE
Force the deployment of different Safe addresses in different networks

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#464]
## Context / issue

The **default behaviour** of the Protocol Kit goes against the vision Safe has on having one address vs. multiple addresses when deploying a Safe to different networks.

## Proposed solution

The Protocol Kit is using the [createProxyWithNonce](https://github.com/safe-global/safe-contracts/blob/main/contracts/proxies/SafeProxyFactory.sol#L52) method with a default `saltNonce` to deploy Safes.

It looks like [createChainSpecificProxyWithNonce](https://github.com/safe-global/safe-contracts/blob/main/contracts/proxies/SafeProxyFactory.sol#LL67C37-L67C37) method does the same by calculating the `chainId` in the contract, but this makes it imposible to redeploy the same address in a different network if some funds need to be recovered. If some funds need to be recovered in another network we should keep it flexible and allow to deploy a Safe in the same address by adding the required `chainId` manually (different than the chain where the funds are stuck and the same as the chain of the original Safe).

For that reason we should add the `chainId` to the `saltNonce` in the SDK when passed to `createProxyWithNonce`.

## Expected result

- Even if the same configuration (owner list, threshold, fallback handler, etc.) is used to deploy a Safe in different networks, the Protocol Kit should generate different addresses.

- Nothing is broken for existing Safes that are already deployed when calculating the Safe address. Even if the `chainId` is added to the `saltNonce` we need to take into consideration that already deployed Safes were deployed with a saltNonce withouth the `chainId`.

**Comment by mmv08** [comment]
I'm unsure if the reasoning behind the chain-specific proxy was the same as in the post you linked. The primary rationale was to use it for some exceptional cases where a Safe must exist on a single network only and nowhere else. I'd not opt-in to use it in the SDK by default because we already know people are prone to mistakes, and this change will remove their safety mechanism.

**Comment by germartinez** [comment]
Thank you @mmv08. I've updated the description to continue using the `createProxyWithNonce` adding the `chainId`.

**Comment by germartinez** [comment]
Thank you @mmv08. I've updated the description to continue using the `createProxyWithNonce` adding the `chainId`.
