### ISSUE TITLE
EthAdapter instead of EthersAdapter

### ISSUE THREAD

**Issue by naelob** [safe-global/safe-core-sdk#473]
## Prerequisites

I am using the last version of the protocol kit and i cant create a safe using `Safe.create({ethAdapter})`. I followed the guides by creating an etherAdapter object but Safe.create is asking for a `EthAdapter` type not `EthersAdapter`.

I even checked the types inside protocol kit sdk and it seems that I found this 
```
export type SafeConfigProps = {
    /** ethAdapter - Ethereum adapter */
    ethAdapter: EthAdapter;
    /** isL1SafeMasterCopy - Forces to use the GnosisSafe L1 version of the contract instead of the L2 version */
    isL1SafeMasterCopy?: boolean;
    /** contractNetworks - Contract network configuration */
    contractNetworks?: ContractNetworksConfig;
};
```
So how can I create an EthAdapter instance, not an EthersAdapter as I saw in the guides ? 

Thank you

ps: Im using ethers 5.7.2 and protocol-kit 1.0.1

## Description
<img width="699" alt="Capture d’écran 2023-07-10 à 13 56 11" src="https://github.com/safe-global/safe-core-sdk/assets/39710677/cb5e31c9-9167-45f2-974a-837b265fc0d8">
<img width="699" alt="Capture d’écran 2023-07-10 à 13 56 30" src="https://github.com/safe-global/safe-core-sdk/assets/39710677/7b7c7357-bbe5-4d4a-b9ff-ee5e3b7ff6ef">

Please describe concisely the bug you have found.

## Environment

- Safe Core SDK version: 
- Safe contract version: 
- Environment:
  - browser
  - non-browser

## Steps to reproduce

If applicable, please provide a screenshot or small video reproducing the bug.
Provide as much information as necessary to reproduce the bug.

## Expected result

Please describe concisely what you expect instead.

**Comment by cesarhuret** [comment]
I am experiencing the same thing

**Comment by cesarhuret** [comment]
@naelob roll back to `@safe-global/protocol-kit@1.0.0` and `@safe-global/safe-core-sdk-types@2.0.0`

**Comment by naelob** [comment]
Thank you !

**Comment by naelob** [comment]
By the way i still encounter this @cesarhuret 
<img width="699" alt="Capture d’écran 2023-07-10 à 19 24 28" src="https://github.com/safe-global/safe-core-sdk/assets/39710677/7238ccc8-4112-48a9-b95b-dfd7af27e99c">

**Comment by dasanra** [comment]
Indeed there was a breaking change on that `safe-core-sdk-types` that was flaged as minor. Using the latest version of both should fix the issue.

As of today
`@safe-global/protocol-kit@^1.2.0`
`@safe-global/safe-core-sdk-types@^2.2.0`
