### ISSUE TITLE
Fix signatures with dinamic part

### ISSUE THREAD

**Issue by germartinez** [safe-global/safe-core-sdk#487]
## Context / issue

[This code](https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/utils/transactions/SafeTransaction.ts#L26-L27) in the `protocol-kit` does not 100% correctly encode signatures. It does not consider the offset, which is required for signatures that have a dynamic part.

## Proposed solution

Might make sense to use the utils methods in `safe-contracts` (see https://github.com/safe-global/safe-contracts/blob/main/src/utils/execution.ts#L142-L174) that are exposed instead of writing the logic again (at least the `v1.3.0` of the package has this available). `safe-tasks` uses this quite heavily.

**Be careful with the `safe-contracts` dependency, as it is a dev-dependency.**

**Be careful: the utils only work when using `ethers` `v5`. They will not work if we update to `ethers` `v6`**

## Alternatives

At least throw an error if dynamic parts are used to make it 100% clear that his is currently not supported yet.

**Comment by mmv08** [comment]
> Be careful with the safe-contracts dependency, as it is a dev-dependency.

You could make it a production dependency.

> Be careful: the utils only work when using ethers v5. They will not work if we update to ethers v6

This particular method doesn't use ethers features, does it?

**Comment by germartinez** [comment]
I just added that as a reminder :P
1) Yes, probably
2) It was shared that the utils didn't work with v6. I didn't check in detail yet.

**Comment by yagopv** [comment]
Integrated in this [PR](https://github.com/safe-global/safe-core-sdk/pull/556)

[Lines](https://github.com/safe-global/safe-core-sdk/blob/d5927980cae6d84d2a58fe3cf45931339fea0506/packages/protocol-kit/src/utils/signatures/utils.ts#L152)
