### ISSUE TITLE
Not able to request transaction to be approved from Metamask to deploy safe, getting error

### ISSUE THREAD

**Issue by sourav-bz** [safe-global/safe-core-sdk#502]
## Description

I am trying to create and deploy Safe using my connected Metamask account to my dApp.
I am creating a signer object like below

`const provider = new ethers.providers.JsonRpcProvider(RPC_URL)`
`ownerSigner = provider.getSigner(public_address)`

and passing the same signer to create `EthersAdapter`

calling `deploySafe()` is not triggering transaction prompt on Metamask for approval.

Getting the following error:

`Uncaught (in promise) Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted: Create2 call failed", method="estimateGas", transaction={"from":"0xA8e55CAa521c6f051F8993853a674FB87B4Fbb03","to":"0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2","data":"0x1688f0b90000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e0000000000000000000000000000000000000000000000000000000000000060b1073742015cbcf5a3a4d9d1ae33ecf619439710b89475f92e2abd2117e90f900000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a8e55caa521c6f051f8993853a674fb87b4fbb03000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":71,\"error\":{\"code\":3,\"message\":\"execution reverted: Create2 call failed\",\"data\":\"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013437265617465322063616c6c206661696c656400000000000000000000000000\"}}","error":{"code":3,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000013437265617465322063616c6c206661696c656400000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0xa8e55caa521c6f051f8993853a674fb87b4fbb03\",\"to\":\"0xa6b71e26c5e0845f74c812102ca7114b6a896ab2\",\"data\":\"0x1688f0b90000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e0000000000000000000000000000000000000000000000000000000000000060b1073742015cbcf5a3a4d9d1ae33ecf619439710b89475f92e2abd2117e90f900000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a8e55caa521c6f051f8993853a674fb87b4fbb03000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":71,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://eth-goerli.g.alchemy.com/v2/dZ88JZEdBCFoeLuNNFWrMRkv2sxLB6SU"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (webpack-internal:///(app-client)/./node_modules/@ethersproject/logger/lib.esm/index.js:231:23)
    at Logger.throwError (webpack-internal:///(app-client)/./node_modules/@ethersproject/logger/lib.esm/index.js:240:20)
    at checkError (webpack-internal:///(app-client)/./node_modules/@ethersproject/providers/lib.esm/json-rpc-provider.js:92:20)
    at JsonRpcProvider.eval (webpack-internal:///(app-client)/./node_modules/@ethersproject/providers/lib.esm/json-rpc-provider.js:591:24)
    at Generator.throw (<anonymous>)
    at rejected (webpack-internal:///(app-client)/./node_modules/@ethersproject/providers/lib.esm/json-rpc-provider.js:22:65)`

## Environment

- Safe Core SDK version: 1.2.0
- Safe contract version: 
- Environment:
  - browser

## Expected result

It's working completely as expected when I am creating signer object using a Private Key.
But I want metamask or any wallet to get triggered for the requested transaction approval and then the Safe needs to get deployed, on approval.

What am i missing here?

**Comment by sourav-bz** [comment]
@germartinez can you help me out here?

**Comment by mmv08** [comment]
Please have a look at https://stackoverflow.com/questions/74160798/why-would-create2-revert. In your case, the transaction fails because you've already deployed an identical safe at this transaction https://goerli.etherscan.io/tx/0xe992a34408531546e9070d06ac28e9d465a92181926af57f08ef2a036440e45a. Since the addresses are deterministic, the same deployment parameters deploy Safes to the same address. You can pass a custom `saltNonce` to `deploySafe` to use a different nonce for deployment.

**Comment by sourav-bz** [comment]
@mmv08 thank you so much, you were right about the SAFE being deployed on the same address.

Tried it with new account. And this is the error it's throwing again. How do i debug this?

`Uncaught (in promise) Error: bad response (status=400, headers={"content-length":"179","content-type":"application/json"}, body="{\"jsonrpc\":\"2.0\",\"id\":74,\"error\":{\"code\":-32600,\"message\":\"Unsupported method: eth_sendTransaction. See available methods at https://docs.alchemy.com/alchemy/documentation/apis\"}}", requestBody="{\"method\":\"eth_sendTransaction\",\"params\":[{\"gas\":\"0x3ff2b\",\"from\":\"0x7e1cfcd7a87c45399e1b23b443af595be793ee2e\",\"to\":\"0xa6b71e26c5e0845f74c812102ca7114b6a896ab2\",\"data\":\"0x1688f0b90000000000000000000000003e5c63644e683549055b9be8653de26e0b4cd36e0000000000000000000000000000000000000000000000000000000000000060b1073742015cbcf5a3a4d9d1ae33ecf619439710b89475f92e2abd2117e90f900000000000000000000000000000000000000000000000000000000000000164b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000140000000000000000000000000f48f2b2d2a534e402487b3ee7c18c33aec0fe5e400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000007e1cfcd7a87c45399e1b23b443af595be793ee2e000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\"}],\"id\":74,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://eth-goerli.g.alchemy.com/v2/dZ88JZEdBCFoeLuNNFWrMRkv2sxLB6SU", code=SERVER_ERROR, version=web/5.7.1)
    at Logger.makeError (webpack-internal:///(app-client)/./node_modules/@ethersproject/logger/lib.esm/index.js:231:23)
    at Logger.throwError (webpack-internal:///(app-client)/./node_modules/@ethersproject/logger/lib.esm/index.js:240:20)
    at eval (webpack-internal:///(app-client)/./node_modules/@ethersproject/web/lib.esm/index.js:244:28)
    at Generator.next (<anonymous>)
    at fulfilled (webpack-internal:///(app-client)/./node_modules/@ethersproject/web/lib.esm/index.js:18:58)`

**Comment by mmv08** [comment]
This seems like a problem with your provider and not an issue with the safe SDK. Please paste the error message into google.
