### ISSUE TITLE
AuthKit 6.1.7 - Type 'OpenloginAdapter' is not assignable to type 'IAdapter<unknown>'.

### ISSUE THREAD

**Issue by luisgj** [safe-global/safe-core-sdk#522]
## Description
When configuring the AuthKit with the Web3Auth Login Adapter we get a compilation error on build due to incompatible typescript types:
```js
Type error: Type 'OpenloginAdapter' is not assignable to type 'IAdapter<unknown>'.
  Types of property 'adapterNamespace' are incompatible.
    Type 'import("/.../node_modules/@web3auth/base/dist/types/chain/IChainInterface").AdapterNamespaceType' is not assignable to type 'import("/.../node_modules/@safe-global/auth-kit/node_modules/@web3auth/base/dist/types/chain/IChainInterface").AdapterNamespaceType'.
      Type '"xrpl"' is not assignable to type 'AdapterNamespaceType'.

  65 |       })
  66 | 
> 67 |       await web3AuthModalPack.init({ options, adapters: [openloginAdapter], modalConfig })
     |                                                          ^
  68 | 
  69 |       web3AuthModalPack.subscribe(ADAPTER_EVENTS.CONNECTED, connectedHandler)
 ```

## Environment

- Safe Core SDK version:  Authkit 1.2.0 with web3auth 6.1.7
- Environment:
  - browser
 
## Steps to reproduce

1. Create a nextjs project and install all the authkit dependencies:
```json
    ...
    "@safe-global/auth-kit": "^1.2.0",
    "@safe-global/safe-react-components": "^2.0.6",
    "@web3auth/base": "^6.1.7",
    "@web3auth/modal": "^6.1.8",
    "@web3auth/openlogin-adapter": "^6.1.7",
```
2. Create a simple component implementing the authkit following the [docs](https://docs.safe.global/safe-core-aa-sdk/auth-kit/web3auth). eg.
```typescript
import { Web3AuthModalPack, Web3AuthConfig } from '@safe-global/auth-kit'
import { Web3AuthOptions } from '@web3auth/modal'
import { OpenloginAdapter } from '@web3auth/openlogin-adapter'


// https://web3auth.io/docs/sdk/pnp/web/modal/initialize#arguments
const options: Web3AuthOptions = {
  clientId: 'YOUR_WEB3_AUTH_CLIENT_ID', // https://dashboard.web3auth.io/
  web3AuthNetwork: 'testnet',
  chainConfig: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: '0x5',
    // https://chainlist.org/
    rpcTarget: 'https://rpc.ankr.com/eth_goerli'
  },
  uiConfig: {
    theme: 'dark',
    loginMethodsOrder: ['google', 'facebook']
  }
}

// https://web3auth.io/docs/sdk/pnp/web/modal/initialize#configuring-adapters
const modalConfig = {
  [WALLET_ADAPTERS.TORUS_EVM]: {
    label: 'torus',
    showOnModal: false
  },
  [WALLET_ADAPTERS.METAMASK]: {
    label: 'metamask',
    showOnDesktop: true,
    showOnMobile: false
  }
}

// https://web3auth.io/docs/sdk/pnp/web/modal/whitelabel#whitelabeling-while-modal-initialization
const openloginAdapter = new OpenloginAdapter({
  loginSettings: {
    mfaLevel: 'mandatory'
  },
  adapterSettings: {
    uxMode: 'popup',
    whiteLabel: {
      name: 'Safe'
    }
  }
})

const web3AuthConfig: Web3AuthConfig = {
  txServiceUrl: 'https://safe-transaction-goerli.safe.global'
}

// Instantiate and initialize the pack
const web3AuthModalPack = new Web3AuthModalPack(web3AuthConfig)
await web3AuthModalPack.init({ options, adapters: [openloginAdapter], modalConfig })
```
3. Build your project with eg. `yarn build | next build` 

## Expected result
The build should compile successfully. Or the docs should have the correct implementation to follow.

## Additional context
A question regarding this same issue was issued on Aug 8th on the Ethereum stack exchange:
https://ethereum.stackexchange.com/questions/153225/openloginadapter-is-not-assignable-to-type-iadapterunknown-using-safecore

It was answered that this issue disappears by using web3auth `4.3.0` 

UPDATE:

I can confirm that downgrading web3auth packages to `4.3.0` removes this error as per the staclk exchange answer.

**Comment by yagopv** [comment]
Hey @myounatan, thanks !!

Can you use the [same versions](https://github.com/safe-global/safe-core-sdk/blob/69296ef3a528c806a58d03ef632b2b383369b029/packages/auth-kit/package.json#L46-L48) we are using in the auth-kit?  I know they are a little behind but as you mention the bug is not there

If you can't, we have plans to revamp the Web3Auth integration with something that fits better the use cases for Safe accounts so in this case, if needed, we recommend the direct usage of the `@web3auth/modal` (we are going to stop using this) and the `@safe-global/api-kit` packages to retrieve the associated Safe accounts as [this is currently](https://github.com/safe-global/safe-core-sdk/blob/4d1c0e14630f951c2498e1d4dd521403af91d6e1/packages/auth-kit/src/AuthKitBasePack.ts#L53C1-L70C4) what the `Web3AuthModalPack` provide as output after the `signIn()`
