### ISSUE TITLE
createAddOwnerTx executes a blank transaction

### ISSUE THREAD

**Issue by franvf** [safe-global/safe-core-sdk#536]
## Description

I'm trying to add a new owner to my Safe Account through the API. These are the steps I'm doing:
**1. Create the adapter**
```
export async function createAdapter(
      adminMnemonic: any,
      providerURL: any,
      adminAddress: string | undefined
    ) {
      const provider = new HDWalletProvider(adminMnemonic, providerURL);
      const web3Instance = new Web3(provider as any);
    
      const ethAdapter = new Web3Adapter({
        web3: web3Instance as any,
        signerAddress: adminAddress,
      });
    
      return ethAdapter;
    }

```
**2. Connect to the safe wallet**
```
export async function safeWalletConnection(
  ethAdapter: any,
  userSafeAddress: any
) {
  const safeSdk = await Safe.create({
    ethAdapter,
    safeAddress: userSafeAddress,
  });

  return safeSdk;
}
```

After executing these two functions, I can check the connection is working because I print some messages with wallet information:
```
const address = await safeSDK.getAddress();
  const owners = await safeSDK.getOwners();
  const threshold = await safeSDK.getThreshold();
  console.log(
    "address: ",
    address,
    " owners: ",
    owners,
    " threshold: ",
    threshold
  );
```
And this log returns:

> address: 0x6B5c63b767b4C70C6371a42B5B854209e361D0C7 owners: [ '0x7Fa68d2da385b9Eaf9009D5E9E7fbf92B79778bd' ] threshold: 1

The problem comes when I execute the createAddOwnerTx function:
```
const tx = await safeSDK.createAddOwnerTx({
      ownerAddress: externalWallet?.wallet_account || "",
    });

    const txResponse = await safeSDK.executeTransaction(tx);
    await txResponse.transactionResponse?.wait();
```
This is the txResponse I'm getting back:

> { hash: '0xfb1aa8862096bce8e90707d16936398758d72fd65330f5965e5887e731de715b', promiEvent: Web3PromiEvent { _emitter: EventEmitter { _events: [Object: null prototype], _eventsCount: 1, _maxListeners: undefined, [Symbol(kCapture)]: false }, _promise: Promise { }, [Symbol(Symbol.toStringTag)]: 'Promise' }, options: { from: '0x7Fa68d2da385b9Eaf9009D5E9E7fbf92B79778bd', gas: '100466' } }

If you check the tx hash on Goerli, you will se the tx is not adding a new owner to my account:
![image](https://github.com/safe-global/safe-core-sdk/assets/36304422/ef15f374-b670-4ee5-b001-442fc6ccd0db)

## Environment

- Safe Core SDK version:  safe-global/protocol-kit: "^1.3.0"
- Safe contract version: 
- Environment:
  Nodejs v16.16.0
  Hardhat 2.17.3
  non-browser

## Expected result

What I'm expecting is that the createAddOwnerTx launch a transaction to add an owner to my safe account, but it is not being added.

## Additional context
- The safe account are being created using my own smart contract, and it performs good in the safe application (I can import it and modify the owner from here)
- The createAddOwnerTx is creating the tx as expected (I have decoded the data and it is ok), but seems the executeTransaction is throwing a blank one.

createAddOwnerTx result:
> EthSafeTransaction {
  signatures: Map(0) {},
  data: {
    to: '0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e',
    value: '0',
    data: '0x0d582f13000000000000000000000000baf91ff22d2f4328183ccb9d683ef458455405b80000000000000000000000000000000000000000000000000000000000000001',
    operation: 0,
    baseGas: '0',
    gasPrice: '0',
    gasToken: '0x0000000000000000000000000000000000000000',
    refundReceiver: '0x0000000000000000000000000000000000000000',
    nonce: 0,
    safeTxGas: '0'
  }
}

- The ownerAddress is defined as expected

**Comment by franvf** [comment]
There is no news about this?

**Comment by DaniSomoza** [comment]
Hi @franvf 

I tried to reproduce this issue in `Goerli` but for me `createAddOwnerTx` is working fine.

I added this new owner `0x8FF80A60905DfC48A275F641F2aDBDef1a709E5E` to my Safe `0x9Fe2725B42a17395f257A0fc0Bf3Ddb703B4c786` and it worked.

```
https://goerli.etherscan.io/tx/0x2f361d6dcff075feb63f48255d85eb56b8f6a6082c99c48a3cfc84ed5cf89834
```

This is my `createAddOwnerTx` result:

```
create owner Transaction:  EthSafeTransaction {
  signatures: Map(0) {},
  data: {
    to: '0x9Fe2725B42a17395f257A0fc0Bf3Ddb703B4c786',
    value: '0',
    data: '0x0d582f130000000000000000000000008ff80a60905dfc48a275f641f2adbdef1a709e5e0000000000000000000000000000000000000000000000000000000000000001',
    operation: 0,
    baseGas: '0',
    gasPrice: '0',
    gasToken: '0x0000000000000000000000000000000000000000',
    refundReceiver: '0x0000000000000000000000000000000000000000',
    nonce: 113,
    safeTxGas: '0'
  }
}
```


Reviewing your transaction it seems that in your `to` field, this [`0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e`](https://goerli.etherscan.io/address/0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e) address is not your Safe address right?

```
EthSafeTransaction {
signatures: Map(0) {},
data: {
to: '0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e',
value: '0',
[...]
```

**Comment by franvf** [comment]
Yeah, it is my safe account, but it is build dynamically and I get it from the DB when it is asigned to a user, then I set that user (an EOA) as owner.

**Comment by DaniSomoza** [comment]
Hi @franvf 

What do you mean with "it is built dynamically"? Are you referring to counterfactual deployment where the Safe Account isn't deployed yet, but you're predicting its address for the user?

**Comment by franvf** [comment]
Hi @DaniSomoza 
No, the Safe Accounts are deployed in batch previously, but they are assigned when a user is registered. Then I add this user as owner, but this is not working

**Comment by mmv08** [comment]
> Hi @DaniSomoza No, the Safe Accounts are deployed in batch previously, but they are assigned when a user is registered. Then I add this user as owner, but this is not working

but the address in your transaction is an empty address, there's no code deployed: https://goerli.etherscan.io/address/0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e

**Comment by DaniSomoza** [comment]
As @mmv08 mention, [in the provided address](https://goerli.etherscan.io/address/0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e) there's no code deployed. Are you sure that you deployed your user's Safe Account?

**Comment by franvf** [comment]
> > Hi @DaniSomoza No, the Safe Accounts are deployed in batch previously, but they are assigned when a user is registered. Then I add this user as owner, but this is not working
> 
> but the address in your transaction is an empty address, there's no code deployed: https://goerli.etherscan.io/address/0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e

That is not the deployment SafeAccount transaction. As I say in the issue description, that is the tx launched when I try to modify the safeAccount's owner. 
I also say that I can get one of the generated SafeAccount and import it using the safe.global web app, and also I can add or modify the owners. The problem is that the tx to modify the owner is not working, because the safeAccount works perfect in the web App

**Comment by franvf** [comment]
> > Hi @DaniSomoza No, the Safe Accounts are deployed in batch previously, but they are assigned when a user is registered. Then I add this user as owner, but this is not working
> 
> but the address in your transaction is an empty address, there's no code deployed: https://goerli.etherscan.io/address/0x92706Aa2eEC418a5c6c39203e5C173fd10CA812e

That address is deployed in mumbai, not in goerli. But I have tried also to generate and add owners in Goerli and didn't works

**Comment by DaniSomoza** [comment]
Hi @franvf,

I apologize for the confusion but I've successfully generated and added owners in `Goerli` without any issues (refer to the transaction [in my initial comment](https://github.com/safe-global/safe-core-sdk/issues/536#issuecomment-1740534056)).

Could you please try again or share more details about the code you're using? This will help me assist you better.

Thanks!

**Comment by dasanra** [comment]
This issue has been with no response for long period and we are not detecting this issue. If you still find issues please feel free to open a new one.
