### ISSUE TITLE
[Ethers v6 Migration] Initial Ethers v6 Integration

### ISSUE THREAD

**Issue by yagopv** [safe-global/safe-core-sdk#544]
## Context / Issue
Initial upgrade to Ethers v6 in the `safe-core-sdk`.

## Proposed solution
Integrate Ethers v6 and create a basic script to use the `protocol-kit` with Ethers v6.

It's expected for the tests and the Hardhat project to fail at this stage.

A separate integration branch will be created, which won't be merged until all migration tasks are completed.

## Links

Ethers migration guide docs: https://docs.ethers.org/v6/migrating/

**Comment by DaniSomoza** [comment]
PR created: https://github.com/safe-global/safe-core-sdk/pull/549
