### ISSUE TITLE
[Web3Auth Safe Signer] Update Safe{Core} SDK example app

### ISSUE THREAD

**Issue by yagopv** [safe-global/safe-core-sdk#566]
## Context
After we release the new `Web3AuthPack`  we need to update the [example application](https://github.com/5afe/account-abstraction-demo-ui) to use this pack

## Proposed solution
Use the new version of the `auth-kit` implementing the `Web3AuthPack` instead the current `Web3AuthModalPack`

## Additional context
[Web3Auth Safe Signer epic](https://www.notion.so/safe-global/Web3auth-Safe-Signer-b3d6c72d3a3047408d992a0130c7d642)

**Comment by JagoFigueroa** [comment]
All good! Tested alongside [this](https://github.com/safe-global/safe-core-sdk/issues/567) ticket
