### ISSUE TITLE
Type Compatibility Issue with Hardhat Ethers Signers in EthersAdapter Initialization

### ISSUE THREAD

**Issue by mshakeg** [safe-global/safe-core-sdk#574]
## Description

There appears to be a type compatibility issue when using `EthersAdapter` with `ethers` version `^6.7.0`. The `HardhatEthersSigner ` obtained from `ethers.getSigners()` is not recognized as a valid type for the `signerOrProvider` property when initializing a new `EthersAdapter`. This seems to be due to a change in the `Signer` interface from `ethers` v5 to v6, which is not yet reflected in the `@safe-global/protocol-kit` package.

## Environment

- Safe Core SDK version: `@safe-global/protocol-kit@1.3.0`
- Safe contract version: NA
- Environment: hardhat

## Steps to reproduce

1. Set up a Hardhat project with the following dependencies:

```json
"devDependencies": {
  "@nomicfoundation/hardhat-ethers": "^3.0.0",
  "ethers": "^6.7.0",
  "@safe-global/protocol-kit": "^1.3.0",
  "@safe-global/safe-core-sdk-types": "^2.3.0",
  "typescript": "^4.9.3"
}
```

2. Write a script that gets a signer which is of type `HardhatEthersSigner`(hardhat-ethers@2 returned a signer of type `SignerWithAddress` which isn't an issue)  and tries to create an `EthersAdapter`:

```typescript
import { ethers } from 'hardhat';
import EthersAdapter from '@safe-global/safe-core-sdk';

async function main() {
  const signer = (await ethers.getSigners())[0];
  const ethAdapter = new EthersAdapter({
    ethers: ethers,
    signerOrProvider: signer, // TypeScript error here
  });
}

main();
```

3. Run the hardhat script with the `--typecheck` flag

The TypeScript error is as follows:

```
test//shared/utils.ts:21:5 - error TS2322: Type 'HardhatEthersSigner' is not assignable to type 'Signer | Provider'.
  Type 'HardhatEthersSigner' is missing the following properties from type 'Signer': _isSigner, getBalance, getTransactionCount, getChainId, and 4 more.
```

## Expected result

The expected result would be that the `HardhatEthersSigner` is compatible with the `Signer | Provider` type required by the `EthersAdapter` constructor, without any TypeScript errors.

## Additional context

This issue seems to be related to the previously reported and resolved issue [#336](https://github.com/safe-global/safe-core-sdk/issues/336), which dealt with the `EthersAdapter` incorrectly treating `Signer` objects as `Provider`. The current type incompatibility might be a regression or a separate issue stemming from updates in the `ethers` library's major version change.

It would be ideal if `@safe-global/protocol-kit` and related types are updated to support the latest `ethers` v6 and `hardhat-ethers` v3 types, ensuring compatibility and developer experience.

**Comment by dasanra** [comment]
The current version of the `protocol-kit` is not compatible with Ethers v6, as mentioned in the docs.

We are currently working to make the `protocol-kit` work with v6, but it includes many breaking changes and will be a major release. https://github.com/safe-global/safe-core-sdk/issues/544

Current `protocol-kit` should be used with Ethers v5.7.2
