### ISSUE TITLE
[Release] Prepare major release 

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#581]
## Context / issue

We had several major changes pending so we decided to create a major release containing a big amount of them. Currently we think there is big enough to publish.

The release PR is ready here:
https://github.com/safe-global/safe-core-sdk/pull/527

The release includes several improvements:
- [refactor(auth-kit): Reduce bundle size](https://github.com/safe-global/safe-core-sdk/pull/523)
- [refactor(protocol-kit): Rename MasterCopy to singleton](https://github.com/safe-global/safe-core-sdk/pull/532)
- [feat(relay-kit): Improve general structure and follow other packs style](https://github.com/safe-global/safe-core-sdk/pull/534)
- [feat: Ethers v6 Migration](https://github.com/safe-global/safe-core-sdk/pull/549)

## Proposed solution

We need to test and update the release.
 - Resolve conflicts with `development` branch
 - Update playground files
 - Publish alpha version
 - Update the current demo UI with the latest packages

**Comment by JagoFigueroa** [comment]
Checking the release we see that there are some issues with the relay kit. Tried in both gnosis chain and goerli via email and metamask and safe creation transaction is being cancelled. Already synced with señor @DaniSomoza and he is checking but so that you are aware: 

![Image](https://github.com/safe-global/safe-core-sdk/assets/92332710/921992b3-d0f8-4026-b5b1-4191d492ccec)

**Comment by dasanra** [comment]
>     * Signing in via WC on the auth kit does not seem to work. Maybe the QR shown is just a placeholder and this is expected? <img alt="Screenshot 2023-11-21 at 17 53 56" width="359" src="https://user-images.githubusercontent.com/92332710/284657266-2bc70160-6cb2-4550-b31b-4c9c06356b19.png">

This was not expected as we didn't configure WalletConnect keys in the demo. Also it was related to v1 and it's deprecated so it should be reviewed for v2 if necessary. I disabled it for now.

**Comment by JagoFigueroa** [comment]
Other than what was reported above, Demo app looks good, giving it my ✅
