### ISSUE TITLE
Support viem

### ISSUE THREAD

**Issue by ennioVisco** [safe-global/safe-core-sdk#594]
Although [viem](https://github.com/wagmi-dev/viem) is the "new kid in town", it provides a very pleasand and efficient API, it is astonishingly well-documented (see it yourselves at [viem.sh](https://viem.sh)), and is becoming popular extremely fast (look at the library trends here: https://npmtrends.com/ethers-vs-viem-vs-web3).

Please consider adding an adapter supporting it!

### Extras
Related stackexchange thread by other people: https://ethereum.stackexchange.com/questions/155920/viemadapter-for-safe-global-protocol-kit?newreg=4a47bdd49aa04caf8c92ae0eec448c46

**Comment by farreldarian** [comment]
I just created a draft for the [ViemAdapter](https://github.com/safe-global/safe-core-sdk/pull/665), still need to check on `GS026` error test

**Comment by ennioVisco** [comment]
@farreldarian perhaps also the strategy of a custom transport implementing EIP-1193 could be a good less-heavy alternative. What do you think? (see https://github.com/safe-global/safe-core-sdk/issues/651)

**Comment by farreldarian** [comment]
> @farreldarian perhaps also the strategy of a custom transport implementing EIP-1193 could be a good less-heavy alternative. What do you think? (see #651)

I designed it to be compatible with any client, allowing you to initialize it with any type of transport. ([ref](https://github.com/farreldarian/safe-core-sdk/blob/e1fe863e5d63b433bdcc299081fd944fff2072d2/packages/protocol-kit/tests/e2e/utils/setupEthAdapter.ts#L42))

```
const adapter = new ViemAdapter({
    client: createClient({
        transport: <your-transport>,
        ...
    })
})
```

**Comment by dasanra** [comment]
Viem is finally supported from @safe-global/protocol-kit v4, as now the kit requires an EIP-1193 provider instead a specific implementation.
