### ISSUE TITLE
Fix Monerium signature decoding on the Demo app

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-core-sdk#600]
Monerium feature on the Onramp kit does not look to work at the moment, clicking on Login on goerli does nothing for me with message: `execution reverted: Hash not approved`

**Comment by DaniSomoza** [comment]
Merged & deployed in the Demo App:
```
https://safe-account-abstraction-demo.netlify.app/
```

**Comment by JagoFigueroa** [comment]
Mi pana! I am getting this warning when accessing the feature:

<img width="1187" alt="Screenshot 2023-11-22 at 14 46 58" src="https://github.com/safe-global/safe-core-sdk/assets/92332710/ef4fb1d1-dbdc-498d-b4d2-6701dc4af324">


Which might be the cause of why I am stuck here:

<img width="660" alt="Screenshot 2023-11-22 at 14 47 40" src="https://github.com/safe-global/safe-core-sdk/assets/92332710/0fb78f92-b1c0-49d5-b874-782683ee8202">

Looks like this Monerium widget should be opening on a new browser tab for me but no bueno, replaces the demo app on the current one preventing any signing pop up 😞

**Comment by JagoFigueroa** [comment]
Working nicely now after some minor changes. Thank you señor Dani for the help too. 

Closing this señor ticket and moving it to done on the sprint board as well 😄
