### ISSUE TITLE
A serious bug caused by the createMemoizedFunction, which results in getSafeContract returning the wrong contract address.

### ISSUE THREAD

**Issue by zhiquan911** [safe-global/safe-core-sdk#634]
I've discovered a serious bug caused by the createMemoizedFunction, which results in getSafeContract returning the wrong contract address.

```
export function createMemoizedFunction<T extends (...args: Parameters<T>) => ReturnType<T>>(
  callback: T,
  cache: Record<string, ReturnType<T>> = {}
) {
  return (...args: Parameters<T>): ReturnType<T> => {
    const key = JSON.stringify(args)

    cache[key] = cache[key] || callback(...args)

    return cache[key]
  }
}
```

This function, when handling the JSON serialization of `EthAdapter`, results in `{}`. This causes an issue when I have two `EthAdapter` from different mainnets, leading to `getSafeContract` returning the wrong address.

For example:

Ethereum's Safe contracts are:
- `gnosis_safe.sol`: `0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552`
- `gnosis_safe_l2.sol`: `0x3E5c63644E683549055b9Be8653de26E0B4CD36E`

OP Mainnet's Safe contracts are:
- `gnosis_safe.sol`: `0x69f4D1788e39c87893C980c06EdF4b7f686e2938`
- `gnosis_safe_l2.sol`: `0xfb1bffC9d739B8D520DaF37dF666da4C687191EA`

When you create safe addresses for the two networks, `createMemoizedFunction` caches the `SafeContract` of Ethereum, causing the address generated later by `OP Mainnet` to be the same as Ethereum. Because the JSON serialization of `EthAdapter` results in `{}`, `createMemoizedFunction` does not record the `EthAdapter` of `OP Mainnet`.

<img width="628" alt="image" src="https://github.com/safe-global/safe-core-sdk/assets/4736643/9afa1d24-a035-46d2-bfc1-008fa99bc6fa">

**Comment by sidrisov** [comment]
I reported the same here: https://github.com/safe-global/safe-core-sdk/issues/598
