### ISSUE TITLE
`TransactionOptions` type missing optional `value` parameter, necessary for when passing value from EOA to Safe

### ISSUE THREAD

**Issue by froggiedev** [safe-global/safe-core-sdk#638]
## Description

In the `Safe.executeTransaction` function, the `options: TransactionOptions` parameter is used, which is later passed to `this.#contractManager.safeContract.execTransaction` to execute the transaction. However, the `TransactionOptions` type is missing an optional `value` parameter, which is necessary for when passing value from EOA to Safe.

Referenced code: https://github.com/safe-global/safe-core-sdk/blob/b369f75df9f1c0c5a6415f212a597b858566378c/packages/protocol-kit/src/Safe.ts#L991C15-L991C33

## Environment

- Safe Core SDK version:
```
    "@safe-global/api-kit": "^2.0.0",
    "@safe-global/protocol-kit": "^2.0.0",
    "@safe-global/safe-core-sdk-types": "^3.0.0",
```
- Safe contract version: v.1.4.1
- Environment: Browser

## Additional context

This is useful to prevent having to first send ETH to a Safe, necessary for a future transaction. Rather, the ETH can be transferred in `value` from the EOA to the Safe to decrease necessary user actions.

**Comment by yagopv** [comment]
Hey @froggiedev. [We evaluated](https://github.com/safe-global/safe-core-sdk/pull/656) this change and found that it works as expected in funding the Safe. However, after internal discussions, we have decided not to implement it. Here are the reasons:

- People may become confused about the transfer `value` when using Safe compared to the `value` using the signer, which has caused problems in the past. It's probably that people start to set the same value in both causing more problems than benefits
-  Setting the `value` in the `execTransaction` options does not provide a significant improvement over sending the transaction with the signer and is unlikely to be a commonly used feature
