### ISSUE TITLE
Umd bundle for @safe-global/auth-kit?

### ISSUE THREAD

**Issue by rho-cassiopeiae** [safe-global/safe-core-sdk#649]
## Context / issue

I want to use SafeAuth in a Flutter Web application for deterministic EOA creation using social login, but need a umd bundle for this.

## Proposed solution

Make it possible to install @safe-global/auth-kit using a `script` tag.

**Comment by dasanra** [comment]
The auth-kit has been deprecated. You can find examples about how to implement 3rd party social login providers [in our docs](https://docs.safe.global/sdk/signers).
