### ISSUE TITLE
[auth-kit] does the new major version of the auth-kit 2.x only supports google social login? 

### ISSUE THREAD

**Issue by paro-paro** [safe-global/safe-core-sdk#652]
`auth-kit` v1.x was using `web3auth/modal` displaying the UI modal with all login options on sign in (fully customizable)

`auth-kit` v2.x leverages `web3auth/safeauth-embed` only displaying google and does not seem to be as configurable as the first version.

So, can you configure the new v2 auth-kit to display the same modal (with all options) from v1? Or how do you trigger, for example, an email passwordless flow?

Thanks!

https://safe-account-abstraction-demo.netlify.app/

https://w3a-safe-demo.vercel.app/

<img width="875" alt="Screenshot 2024-01-06 at 19 33 15" src="https://github.com/safe-global/safe-core-sdk/assets/43136874/1626033d-133d-448a-9a29-0064ee6b44e5">

<img width="884" alt="Screenshot 2024-01-06 at 19 31 57" src="https://github.com/safe-global/safe-core-sdk/assets/43136874/42b104e4-4d5e-435f-80b2-13eba2185f3a">

**Comment by paro-paro** [comment]
Checking out the source, I've seem that there is a `loginProvider` option you can pass on `signIn()`. I guess now we have to build our own modal with the social login options we want to support? 

Testing out locally this [demo app](https://github.com/5afe/safe-core-sdk-demo/tree/main) I get errors when changing the loginProvider to, for example, `github` or `email_passwordless` 

```ts
  // auth-kit implementation
  const loginWeb3Auth = useCallback(async () => {
    if (!safeAuthPack) return

    try {
      const { safes, eoa } = await safeAuthPack.signIn({
        loginProvider: 'email_passwordless' // 'github'
      })
```

<img width="653" alt="Screenshot 2024-01-06 at 20 00 30" src="https://github.com/safe-global/safe-core-sdk/assets/43136874/72b006ea-8079-4069-89b1-7d188e54e532">

**Comment by dasanra** [comment]
@paro-paro hey, thank you for your ticket.

Currently this is the expected behavior. v2 adds the capacity to use the same Safe across different dApps. As starting point we added support for Google accounts only, but we are working to add support for the other providers as soon as possible.

Keep checking our future versions where we will add this support again.

**Comment by paro-paro** [comment]
Hi @dasanra 

Thanks for the info!!
