### ISSUE TITLE
[4337] Research the execution flow

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#683]
## Context / issue

Executing a transaction using the 4337 module involves many steps. From the transaction creation, that should include an UserOperation element (SafeOperation) to the signing of the hash, and the final call to the bundler in order to execute the transaction.

## Proposed solution
- [Check the execution flow diagram created by the protocol team](https://github.com/safe-global/safe-modules/tree/main/modules/4337#execution-flow)
- Propose how the flow could look like using the `protocol-kit`. Suggest methods to be created in the `4337Pack` and how the flow should look like from the developer perspective before implementing the methods.

## Additional context

 - Remember that only Safes v1.4.1 or later are compatible with 4337 module.

**Comment by yagopv** [comment]
https://www.notion.so/safe-global/4337-SDK-implementation-853f5e84306943ba8e10e247d751f76c
