### ISSUE TITLE
[4337] Implement sign user operation

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#685]
## Context / issue

Signs an user operation to allow the bundler to execute a transaction.

## Proposed solution

Implement a method in the `4337Pack` to allow signing a `UserOperation`

**Comment by yagopv** [comment]
Implemented in [signSafeUserOperation()](https://github.com/safe-global/safe-core-sdk/blob/025910756c77ce2f21f2fc75344163c125b66974/packages/relay-kit/src/packs/safe-4337/Safe4337Pack.ts#L103-L145)
