### ISSUE TITLE
[4337] Deploy a testing Safe

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#686]
## Context / issue

To unlock developing of transaction execution while we polish the Safe deployment flow we need to create some testing Safes that are already setup with the 4337 module.

## Proposed solution

 - Manually create Safes in Sepolia with 4337 module enabled.

**Comment by yagopv** [comment]
Resolved with https://github.com/safe-global/safe-core-sdk/blob/025910756c77ce2f21f2fc75344163c125b66974/playground/relay-kit/deploy-4337-safe.ts
