### ISSUE TITLE
SafeProxy contract is not deployed on the current network

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-core-sdk#689]
I am trying to send ETH from my safe wallet.

Safe address : 0x159bD467fafcfA348D2b5f357b23aA1d70E814A0

```

.proposeTransaction({
        safeAddress: checksumSafeAddresss,
        safeTransactionData: safeTransaction.data,
        safeTxHash,
        senderAddress: await owner1Signer.getAddress(),
        senderSignature: senderSignature.data,
      });
```

I am getting the error "**SafeProxy contract is not deployed on the current network**" 

On **_Sepolia Network_**.

Note : I am doing it using code not using UI of safe.

**Comment by Malikrehman00107** [comment]
Hi Gnosis team, kindly consider looking into this issue which is not resolved yet.
@katspaugh @rudolfs @vorot93 @koeppelmann

**Comment by Malikrehman00107** [comment]
![image (8)](https://github.com/safe-global/safe-core-sdk/assets/111962911/73ca3c3b-deb1-46fb-8841-71ad88d801a5)

Hi Gnosis team, kindly consider looking into this issue which is not resolved yet.
@katspaugh @rudolfs @vorot93 @koeppelmann

**Comment by Malikrehman00107** [comment]
![image (9)](https://github.com/safe-global/safe-core-sdk/assets/111962911/53a05d73-7a97-4b91-bd4c-f7dcc3a9efd9)

**Comment by compojoom** [comment]
Are you sure that the RPC you use is correct and that your SAFE_ADDRESS configured in the configService is correct?
If you look at the code in the safeDeploymentContracts.ts:
https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/contracts/safeDeploymentContracts.ts#L128
It's tryign to fetch the contract code from the network. Apparently for your safe this fails - you are either are passign wrong address or the RPC call is failing.

**Comment by Malikrehman00107** [comment]
@faisal-anwar825


have a look at this please

**Comment by katspaugh** [comment]
It can happen if your wallet is on the wrong chain.

**Comment by Malikrehman00107** [comment]
@katspaugh  thats not the case here!

**Comment by katspaugh** [comment]
Replace where?

**Comment by Malikrehman00107** [comment]
@katspaugh !

**Comment by katspaugh** [comment]
In what code?

**Comment by Malikrehman00107** [comment]
@katspaugh please check the attachments in start convo!

**Comment by katspaugh** [comment]
There’s no tx service URL in the attached code, so I’m not sure what exactly you’re replacing.

Are you following this guide? https://github.com/safe-global/safe-core-sdk/blob/main/guides/integrating-the-safe-core-sdk.md

**Comment by katspaugh** [comment]
The error you’re getting has nothing to do with proposing or the transaction service.

It cannot find a ProxyFactory contract on the chain your provider is on.

So as compojoom indicated above, check your provider and its RPC URL. L

**Comment by Malikrehman00107** [comment]
are you ref to this one : Are you following this guide? https://github.com/safe-global/safe-core-sdk/blob/main/guides/integrating-the-safe-core-sdk.md ?

**Comment by Malikrehman00107** [comment]
@katspaugh  Thank you so much !
