### ISSUE TITLE
`getAllTransactions` does not parse options properly

### ISSUE THREAD

**Issue by clemsos** [safe-global/safe-core-sdk#690]
## Description

When using the `getAllTransactions` with options following `AllTransactionsOptions` type to get only the safe txs that havent been executed yet. When changing the options, the results are not affected. The URL seems to be constructed correctly (I see it in the log) but for some reasons even changing the params in the URL does not seem to affect the number of results shown.

Not sure what I am missing ?

example:

```js
const allTxs = await safeService.getAllTransactions(multisig, {
  executed: false,
  trusted: false,
  queued: true,
})
```

https://safe-transaction-mainnet.safe.global/api/v1/safes/0x9168EABE624e9515f3836bA1716EC1DDd4C461D4/all-transactions/?executed=false&limit=20&offset=20&queued=true&trusted=false

## Environment

- Safe Core SDK version: 
- Safe contract version: 
- Environment:
  - browser
  - non-browser

## Steps to reproduce

1. create a ethers provider
2. initialize an eth adapter
3. initialize service with `SafeApiKit`
4. fetch all txs using options

```js
const provider = await getProvider(chainId)
const ethAdapter = new EthersAdapter({
  ethers,
  signerOrProvider: provider,
})

// get Safe service
const safeService = new SafeApiKit({
  chainId,
  txServiceUrl: safeServiceURLs[chainId] || null,
})
const allTxs = await safeService.getAllTransactions(multisig, {
  executed: false,
  trusted: false,
  queued: true,
})
```

which gives 

```
{
  count: 120,
  next: 'https://safe-transaction-mainnet.safe.global/api/v1/safes/0x9168EABE624e9515f3836bA1716EC1DDd4C461D4/all-transactions/?executed=false&limit=10&offset=10&queued=true&trusted=true',
  previous: null,
  results: [
...
```
## Expected result

I will expect the already executed to be hidden when selecting `executed: false` but they are still returned by the API.

**Comment by dasanra** [comment]
If you want to get the pending transactions you can use the `getPendingTransactions` method instead.
