### ISSUE TITLE
Creating a rejection transaction should have safeTxGas 0 (for Safes <1.3.0)

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-core-sdk#694]
## Description

The `createRejectionTransaction` actually tries to set the safeTxGas to 0. 
This gets overwritten later on for Safes with version < 1.3.0 though.

This causes the client Gateway to not correctly detect these as onchain Cancellation / Rejection transactions.

## Environment

- Safe Core SDK version:  `"@safe-global/protocol-kit": "3.0.0"`
- Safe contract version: 1.1.1
- Environment:
  - browser
  - non-browser

## Steps to reproduce

Call createRejectionTransaction for a Safe <1.3.0.
Observe that SafeTxGas gets estimated and set.

## Expected result
SafeTxGas is 0

## Additional context
- Bug on Safe {Wallet} web: https://github.com/safe-global/safe-wallet-web/issues/3171
- Issue on CGW that introduced check for SafeTxGas to be 0: https://github.com/5afe/safe-client-gateway/issues/286

**Comment by dasanra** [comment]
After some testing it was found that `protocol-kit` value was overwriten in the web interface
