### ISSUE TITLE
[4337] Add update paymaster options function

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#733]
## Context / issue

Currently is only possible to set paymaster configuration when initializing the 4337Pack. It would be nice if possible to update the paymaster configuration without sending all parameters again creating a new instance.

## Proposed solution

Create a `setPaymaster` function that allows changin the paymaster configuration without reloading the whole pack.

**Comment by DaniSomoza** [comment]
After reviewing the implementation effort required to regenerate the `initCode` outside if the `init()` function and considering that the use case would be somewhat anecdotal, **we will not implement this ticket.**

Developers can have the same functionality by simply calling the `init()` function again with the new paymaster options.
