### ISSUE TITLE
Function execTransaction is failing

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-core-sdk#768]
We create a safe and when we send the funds form safe.

execTransaction( Is failing .

Here is Trx Hash: https://sepolia.etherscan.io/tx/0x02cbb2c32af0ae333d90e704a630d3638b53005ba9dbb3022028521b8fe9d71d

Safe Smart Contract : https://sepolia.etherscan.io/address/0x159bd467fafcfa348d2b5f357b23aa1d70e814a0

need your attention here please

**Comment by Malikrehman00107** [comment]
`const provider = new ethers.providers.JsonRpcProvider(
sepoliaRpcUrl,
);
const owner1Signer = new ethers.Wallet(
firstOwnerPrivateKey,
provider,
);

const ethAdapterOwner1 = new EthersAdapter({
ethers,
signerOrProvider: owner1Signer,
});

const safeService = new SafeApiKit({
txServiceUrl: SepoliaTransactionServiceUrl,
ethAdapter: ethAdapterOwner1,
});

const value = ethers.utils
.parseUnits(amount.toString(), token.decimals)
.toString();

const tokenContract = new ethers.Contract(token.contractAddress, erc20Abi, provider)

const data = tokenContract.interface.encodeFunctionData('transfer', [address, value]);

const safeTransactionData: SafeTransactionDataPartial = {
to: ethers.utils.getAddress(token.contractAddress),
data,
value
};

const safeSdk: Safe = await Safe.create({
ethAdapter: ethAdapterOwner1,
safeAddress: safeAddress,
});

// Create a Safe transaction with the provided parameters
const safeTransaction = await safeSdk.createTransaction({
safeTransactionData
});
console.log(Owner 1 creates a transction..);

// Deterministic hash based on transaction parameters
const safeTxHash = await safeSdk.getTransactionHash(safeTransaction);

// Sign transaction to verify that the transaction is coming from owner 1
const senderSignature = await safeSdk.signTransactionHash(safeTxHash);
const checksumSafeAddresss = ethers.utils.getAddress(
safeAddress,
);
await safeService.proposeTransaction({
safeAddress: checksumSafeAddresss,
safeTransactionData: safeTransaction.data,
safeTxHash,
senderAddress: await owner1Signer.getAddress(),
senderSignature: senderSignature.data,
});

const owner2Signer = new ethers.Wallet(this.configService.get('OWNER_2_PRIVATE_KEY'), provider)
const ethAdapterOwner2 = new EthersAdapter({
ethers,
signerOrProvider: owner2Signer
})

const safeSdkOwner2 = await Safe.create({
ethAdapter: ethAdapterOwner2,
safeAddress: this.configService.get('SAFE_ADDRESS')
})

const signature = await safeSdkOwner2.signTransactionHash(safeTxHash)
await safeService.confirmTransaction(safeTxHash, signature.data)

const safeSdk: Safe = await Safe.create({ ethAdapter: ethAdapterOwner1, safeAddress })

const safeTransactionE = await safeService.getTransaction(safeTxHash)
const executeTxResponse = await safeSdk.executeTransaction(safeTransactionE)`

**Comment by Malikrehman00107** [comment]
This is the code that i am using to transfer tokens from safe to a wallet. and i am getting success on the execute transaction. but when seen on block explorer there is an error in transaction like mentioned in the original issue above.

**Comment by Malikrehman00107** [comment]
@faisal-anwar825

**Comment by Malikrehman00107** [comment]
@germartinez

**Comment by dasanra** [comment]
There is an issue with the internal transaction. As the token contracts is not verified is very difficult to debug, but the error is affecting the internal transaction. Two things may be happening:

1.- The transfer function is not used correctly, or you are not fulfilling some of the transfer function `requires`
2.- I see you are setting the `safeTxGas`. Can't see it in the code example but indeed is set in the test functions you set. You should leave this value unset or 0. 

Appart from the points above, there is another error. In the `safeTransactionData` you set the `value` parameter to be equal to the value of ERC20 token you want to send. The `value` in `safeTransactionData` is meant only to transfer native tokens (Sepolia ETH in this case) and you shouldn't set it with the same variable as the ERC20 token `value`. You should set it explicitly to `0`.

```
const safeTransactionData: SafeTransactionDataPartial = {
  to: ethers.utils.getAddress(token.contractAddress),
  data,
  value: 0
};
```

Please test with this changes

**Comment by Malikrehman00107** [comment]
@faisal-anwar825

**Comment by Malikrehman00107** [comment]
@germartinez @dasanra

**Comment by Malikrehman00107** [comment]
@dasanra https://sepolia.etherscan.io/address/0x34A50a7A272E86EE30b7A74E36f3f02AF18B1eB5

here is verified source contract

**Comment by Malikrehman00107** [comment]
@yagopv please!

**Comment by dasanra** [comment]
@Malikrehman00107 please, don't tag people like that.

@faisal-anwar825 The error now is self explanatory, the account that executes the transaction (the signer) doesn't have enough ETH to execute the transaction. Add funds to `[0xb55D2195F400A137Fa67EB520B13B6b951770b76](https://sepolia.etherscan.io/address/0xb55d2195f400a137fa67eb520b13b6b951770b76)`

**Comment by Malikrehman00107** [comment]
@dasanra 
My apologies, this issue has been stuck for days and testing is still pending that is why

**Comment by dasanra** [comment]
I see you are executing now transactions with the correct configuration. We don't have any error like the one you describe above, so I would need to see a current version of the code to help further

**Comment by dasanra** [comment]
@Malikrehman00107 that contract is just a Safe contract.

I would need to see either the current SDK implementation and the code of this smart contract
https://sepolia.etherscan.io/address/0x419Fe9f14Ff3aA22e46ff1d03a73EdF3b70A62ED

**Comment by dasanra** [comment]
@faisal-anwar825 could you remove the safeTxGas from `safeTransactionData`?

Also, could you tell me which versions of the SDK are you using?

Could you tell me which line the code is failing? Does it fails when creating the transaction or already when sending it to the blockchain?

Could you leave in the queue, pending to be executed a transaction that is created with the script?
I can see several transactions sucessfully executed in the interface, how are you executing them?

**Comment by dasanra** [comment]
Ok, those are old versions that are not supported anymore. There were some gas estimation issues that were solved in v2 specially affecting some specific RPC providers, which may be your case.

To go forward with this topic you will need to upgrade to the latest version:
```
"@safe-global/api-kit": "^2.3.0",
"@safe-global/protocol-kit": "^3.0.2"
```

From v2 you will need to use ethers v6, that is the supported version.

There are also some migration guides explaining bigger changes between the version you are using and the new one, just in case you are affected:

https://docs.safe.global/sdk/api-kit/reference/migrating-to-v2
https://docs.safe.global/sdk/protocol-kit/reference/migrating-to-v2

**Comment by dasanra** [comment]
Yes, that is expected. 

From `api-kit`v2 is not necessary to specify the transaction service URL if you use [one of the public available ones](https://docs.safe.global/advanced/api-supported-networks).

You can instead just leave the chainId parameter only.
With this change we also removed a mandatory internal `/api/`element because we were forcing every custom API to contain that structure. If you still want to specify the transaction service URL you should change the one stored in `awsConfig` to be `https://safe-transaction-sepolia.safe.global/api`

This will fix the current error that is displayed in your app.

**Comment by Malikrehman00107** [comment]
@dasanra  sorry to bother you , Can you have a look at this, please? 

Best

**Comment by Malikrehman00107** [comment]
@germartinez can you please guide ? it seems daniel is away since few days

**Comment by Malikrehman00107** [comment]
@dasanra  can you please review and do necessary? 

best

**Comment by Malikrehman00107** [comment]
@yagopv 

can you please check in with your colleagues this issue has been pending for the last 2 weeks.

Best

@dasanra  attentive

**Comment by dasanra** [comment]
@faisal-anwar825 I see you are creating plenty of transactions currently with 2 signatures. But is not possible to execute those transactions because the previous transactions should be executed first

https://app.safe.global/transactions/queue?safe=sep:0x159bd467fafcfa348d2b5f357b23aa1d70e814a0

While all those transactions are in the queue it won't be possible for you to run the script completely, as the execute function will be locked because is not having the next nonce to execute.

**Comment by Malikrehman00107** [comment]
@faisal-anwar825  all good here ?

**Comment by Malikrehman00107** [comment]
@dasanra  we are still facing the issue with the nonce , every time transaction  get stucked end up a mess in the backlog.

please propose a permanent and effective solution.

best regards

**Comment by dasanra** [comment]
@Malikrehman00107 from what I can see in the Safe you shared in the thread transactions are being executed sucessfully, so unless you provide more context for us everything looks good.

**Comment by dasanra** [comment]
After checking there are several transactions executed that seem automated we consider this issue as closed.
