### ISSUE TITLE
Update safe-deployment version to v1.36.0

### ISSUE THREAD

**Issue by happyleow** [safe-global/safe-core-sdk#814]
## Context / issue

I was referring to the comment in the GitHub issue(https://github.com/safe-global/safe-infrastructure/issues/124#issuecomment-1877097932) to operate the `safe-infrastructure` ourselves.

## Proposed solution

`safe-deployment` v1.36.0 supports the Eclipse Testnet we want.
So we want to update `safe-deployment` version to v1.36.0 in the `safe-core-sdk`(composed of several packages including protocol-kit) repo and then release the new `safe-core-sdk` version.

## Additional context

- Safe-deployment v1.36.0: https://github.com/safe-global/safe-deployments/releases/tag/v1.36.0

**Comment by happyleow** [comment]
Could you give me an idea of how long this will take to process?
This is a high-priority task for us, we would greatly appreciate it if you could expedite the processing.
Thank you for your understanding.

**Comment by dasanra** [comment]
If you use the following versions you should have it available
 - `protocol-kit` v3.1.1
 - `safe-core-sdk-types` v4.1.1

**Comment by happyleow** [comment]
@dasanra Thanks for your prompt response, but I want to double-confirm this thing.
Have you already released `protocol-kit` v3.1.1 and `safe-core-sdk-types` v4.1.1?
The latest release version(`safe-core-sdk` r38, released 2 weeks ago) has `protocol-kit`: v3.1.0 and `safe-core-sdk-types`: v4.1.0.

**Comment by dasanra** [comment]
Yes, I've just released those package versions today, still not showing in the github releases but they are available on npm

**Comment by happyleow** [comment]
@dasanra That's great, i will be waiting for it. :)

**Comment by happyleow** [comment]
Great, thank you for your support!
