### ISSUE TITLE
Incompatibility detected: The current Safe Account version (1.3.0) is not supported. EIP-4337 requires the Safe to use at least v1.4.1.'

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-core-sdk#843]
We are adding relay for our safe to pay the fee directly from the safe instead of owner wallet.

We are following this documentation using :https://docs.safe.global/sdk/relay-kit/guides/4337-safe-sdk

We are getting this error : Incompatibility detected: The current Safe Account version (1.3.0) is not supported. EIP-4337 requires the Safe to use at least v1.4.1.'

**Comment by dasanra** [comment]
This is expected. You are trying to use a v1.3.0 Safe and when using 4337 the Safe must be v1.4.1. Currently there is no way to migrate existing Safes to v1.4.1 + 4337 support, so a new one should be created for this case.

Also you need to know that currently Safes having 4337 module enabled can't be used through the web interface (https://app.safe.global). If this is needed I encourage you to wait for it to be added. There is no expected date for this yet.

When finding this kind of errors, please post on Stack Exchange, as recommended by our [support guidelines](https://github.com/safe-global/safe-core-sdk/blob/main/SUPPORT.md). 

In this case it's true this information may be missing and we will add it to the docs, but still is not an issue with the SDK.

**Comment by Malikrehman00107** [comment]
@dasanra

 can you please guide with the new safe deployment process?

Using this method : https://docs.safe.global/sdk/relay-kit/guides/4337-safe-sdk
