### ISSUE TITLE
[Research] Example React Hooks

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#847]
## Context / issue

Many developers that want to integrate the Safe Core SDK want to use React as their web framework. Currently we don't offer any tooling specific for this case, which makes more difficult to kickstart a project.

## Proposed solution

Research React Hooks that may be useful for developers to integrate the Core SDK with their Dapps.
 - Find common user flows that could be covered.
 - Find flows using different kits (relay+protocol) that could make sense to bundle as an unique tool.
 - Focus in flows using api, protocol and relay kit.
 - Prepare repository structure, consider it a mono repo for developer tooling that uses the Core SDK.

**Comment by tmjssz** [comment]
Research document can be found [here](https://www.notion.so/safe-global/Safe-React-Hooks-Research-9fae1d7256fa4e0daef21b7f5f25c835?pvs=4)
