### ISSUE TITLE
[Research] SDK Refactor

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#848]
## Context / issue

Currently the SDK is composed of several kits. Some of them have wide adoption while some others are not that extended. Also we would like to provide a package that target specific user flows, like 1 signer Safes for developers to onboard to the SDK on an easier and simpler way.

## Proposed solution

Should create a package covering the base flows needing a minimal configuration.
 - It should expose only the minimum functionality to work with a Safe
 - It should cover the most common Safe configurations

**Comment by yagopv** [comment]
[Research document](https://www.notion.so/safe-global/SDK-Refactor-4e45fd5f454d4715a60e72d4854b9aa9)
