### ISSUE TITLE
Unable to perform transaction using Safe4337Module with safe-core-sdk

### ISSUE THREAD

**Issue by faisal-anwar825** [safe-global/safe-core-sdk#927]
I am using a multi-signature safe to handle withdrawal of funds to wallets. Issue is i have to maintain the eth balance in owner wallet addresses in order to pay gas fee for transactions. To avoid that i am trying to use Safe4337Module with pimlico so that the gas fee can be paid from within the safe but when i try to perform a transactions it gets bulked with other transaction which i have no idea where they came from.
Below is my code where i create, sign and execute transaction.

`

          const safe4337Pack1: Safe4337Pack = await Safe4337Pack.init({
                  provider: withdraw.token.blockchain.rpcUrl,
                  signer: OWNER1_DECRYPTED,
                  bundlerUrl: `https://api.pimlico.io/v1/sepolia/rpc?apikey=${pimlico_api_key}`,
                  options: {
                    safeAddress: '0x42B13074486F87A0CfbEac9a997b345730B4bc97'
                  }
                })
          
                const safe4337Pack2: Safe4337Pack = await Safe4337Pack.init({
                  provider: withdraw.token.blockchain.rpcUrl,
                  signer: OWNER2_DECRYPTED,
                  bundlerUrl: `https://api.pimlico.io/v1/sepolia/rpc?apikey=${pimlico_api_key}`,
                  options: {
                    safeAddress: '0x42B13074486F87A0CfbEac9a997b345730B4bc97'
                  }
                })
          
                const safe4337Pack3: Safe4337Pack = await Safe4337Pack.init({
                  provider: withdraw.token.blockchain.rpcUrl,
                  signer: OWNER3_DECRYPTED,
                  bundlerUrl: `https://api.pimlico.io/v1/sepolia/rpc?apikey=${pimlico_api_key}`,
                  options: {
                    safeAddress: '0x42B13074486F87A0CfbEac9a997b345730B4bc97'
                  }
                })
                
                const safeOperation = await safe4337Pack1.createTransaction({
                    transactions: [
                      {
                        to: checksumAddresss,
                        value,
                        data: '0x',
                      },
                    ],
                  });
          
                  // Sign the user operation with Owner 1
                  const signedSafeOperation1 = await safe4337Pack1.signSafeOperation(safeOperation);
          
                  // Sign the user operation with Owner 2
                  const signedSafeOperation2 = await safe4337Pack2.signSafeOperation(signedSafeOperation1);
          
                  // Sign the user operation with Owner 3
                  const signedSafeOperation3 = await safe4337Pack3.signSafeOperation(signedSafeOperation2);
          
                  // Execute the user operation
                  const userOperationHash = await safe4337Pack1.executeTransaction({
                    executable: signedSafeOperation3
                  })
          
                  while (!userOperationReceipt) {
                    // Wait 2 seconds before checking the status again
                    await new Promise((resolve) => setTimeout(resolve, 2000))
                    userOperationReceipt = await safe4337Pack1.getUserOperationReceipt(
                      userOperationHash
                    )
                  }

`

Now i tried to withdraw 0.0059 ETH from my safe using the above code. and this is the resulting transaction hash

[https://sepolia.etherscan.io/tx/0x9995db890bd3bf8d8bbb89a0a00df47722614fe68dff228c781d6abead24e7ef](url)

Instead of 0.0059 eth a lot more than that is deducted from my safe. Plus something from the owner wallet as well. The primary purpose of all this was to avoid paying anything from owner wallets.

Another thing is the transaction that i provided above is initiated by one of the owners instead of safe contract address. and i don't understand the other two transactions that are batched in this hash.

Could someone from the team guide me about whats happened in this transaction and where the problem lies. is it at my end?

**Comment by dasanra** [comment]
Hey @faisal-anwar825 if you check carefully the transaction you will see everything is correct.

- You want to transfer 0.0059 eth, and that was sent to `0x7760...a722` that should be the address you selected with `checksumAddress`

 - Transfer of `0.015844 ETH` is the amount that your Safe pays to get the transaction executed, the entry point selects that amount with some margin for gas price fluctuations and a fee.

 - Transfer of `0.007716 ETH` is not from any of your owners, is from the entrypoint paying the executor the real cost of sending the transaction.

No funds were deducted from any of your owners in that transaction.

You can see that the real transaction cost was `0.00674194 ETH` wich is a bit less thant the executor received, and then your Safe payed extra on top of that because the margin and fee that the entrypoint sets.

**Comment by dasanra** [comment]
Closing this ticket as there are no issues related with code.
