### ISSUE TITLE
[SDK Refactor] Research Viems 4337 compatibility

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#946]
## Context / issue

Viem currently released a version which is able to use 4337 to execute transactions. We need to investigate how this can match the extend system and if it would be possible to use Safes + 4337 directly with Viem

## Proposed solution

We were able to extend Viem with Safe actions in #918. We need to research if it would be possible to use the Safe only with Safe actions and Viem.

## Alternatives

Research if Viem could reduce the amount of code in the relay kit to improve its maintenance.

## Additional context

It would be nice if developers that are more familiar with Viem would be able to use the Safe with a more Viem native approach.

**Comment by yagopv** [comment]
https://www.notion.so/safe-global/Integrate-Safe-with-new-viem-Account-Abstraction-features-9a0502342c264131838ebf9ce9b2ee8d
