### ISSUE TITLE
Outdated examples in documentation

### ISSUE THREAD

**Issue by InoMurko** [safe-global/safe-core-sdk#961]
## Description

https://docs.safe.global/sdk/api-kit
```
Initialize the API Kit
```
step has been deprecated, does not work the way it's documented.

```
TypeError: SafeApiKit is not a constructor
    at main (file:///Users/opt/arbitrum-orbit-sdk/examples/setup-fast-withdrawal/dist/1-create_multisig.js:67:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.9.0

    "@safe-global/api-kit": "^2.4.5",
    "@safe-global/protocol-kit": "^4.1.0",
    "@safe-global/safe-core-sdk-types": "^5.1.0"
```

## Environment
- Safe Core SDK versions:
```
    "@safe-global/api-kit": "^2.4.5",
    "@safe-global/protocol-kit": "^4.1.0",
    "@safe-global/safe-core-sdk-types": "^5.1.0"
```
- Safe contract version: 
- Environment:
  - non-browser

## Steps to reproduce

If applicable, please provide a screenshot or small video reproducing the bug.
Provide as much information as necessary to reproduce the bug.

## Expected result

Please describe concisely what you expect instead.

**Comment by josevazf** [comment]
To initialize the API Kit you should use the default export:
```Typescript
const apiKit = new SafeApiKit.default({
  chainId: 1n
})
```

**Comment by InoMurko** [comment]
Oh yeah, I got it figured out. What needs to be added maybe is that NodeNext must be used for moduleResolution. `node` does not work.

**Comment by dasanra** [comment]
We need to add to the docs information that currently the Kits only have commonjs build. This should be considered when used in module based builds.
