### ISSUE TITLE
[auth-kit] Examples does not work

### ISSUE THREAD

**Issue by CelestialBreeze915** [safe-global/safe-core-sdk#969]
## Description

auth-kit examples does not work.

## Environment
- Safe Core SDK versions:
  - auth-kit: 2.0.9
- Environment:
  - browser

<img width="1312" alt="image" src="https://github.com/user-attachments/assets/03eeed8f-2031-4772-9f4b-86aff3c4a68b">

**Comment by dasanra** [comment]
@CelestialBreeze915 thank you for your comment. The auth-kit is being deprecated.

Here you can find information on how to use Web3Auth latest version with the Core SDK
https://docs.safe.global/sdk/signers/web3auth
