### ISSUE TITLE
How to update safe version that is already deployed to mainnet ?

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-core-sdk#976]
Hi! 

Please guide how we can update the safe version, cause we need the version [v1.4.1] in order to implement relays.

Best

**Comment by dasanra** [comment]
Please, use the indicated support channels

https://ethereum.stackexchange.com/questions/164472/how-to-update-the-safe-global-version?r=SearchResults&s=2%7C32.4869

Currently is still not possible to update a 1.3.0 Safe to a 1.4.1. The team is working in order to allow this.
