### ISSUE TITLE
[Research] React Native compatibility

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-core-sdk#991]
## Context / issue

Currently we don't provide any SDK for enabling mobile development using Safe Smart Account. Many developers have signaled this would be something they would be interested about. It's worth to review the possibility of creating such a kit.

## Proposed solution

Let's start reviewing potential compatibility of React Native with our current SDK. We need to detect:
 - Is our build compatible with React Native?
 - Which areas of our SDK should be refactored to be fully compatible?
 - Can React Native interact using passkeys in mobile devices?

**Comment by yagopv** [comment]
The tests and compatibility results are reflected in this [document](https://www.notion.so/safe-global/Research-React-Native-compatibility-11c8180fe5738029902bf00a788b340b)
